apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: external
  namespace: system-gateway
  annotations:
    external-dns.alpha.kubernetes.io/target: "${gateway_dns_target}"
spec:
  listeners:
    - name: dns-udp
      protocol: UDP
      port: 53
      allowedRoutes:
        namespaces:
          from: All
        kinds:
          - kind: UDPRoute
    - name: dns-tcp
      protocol: TCP
      port: 53
      allowedRoutes:
        namespaces:
          from: All
        kinds:
          - kind: TCPRoute
