apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kibana
  namespace: system-observability
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: kibana
      # renovate: datasource=helm depName=kibana package=kibana helmRepo=https://helm.elastic.co
      version: "8.5.1"
      sourceRef:
        kind: HelmRepository
        name: elastic-kibana
  values:
    # renovate: datasource=docker depName=docker.elastic.co/kibana/kibana package=docker.elastic.co/kibana/kibana
    image: docker.elastic.co/kibana/kibana:9.3.4@sha256:c0ba2d8f48ab79a2478d82668b4a9a3878e73d037d7e15797c3aca9bad7f5962
    kibanaConfig:
      kibana.yml: |
        elasticsearch.ssl.certificateAuthorities: ["/usr/share/kibana/config/certs/ca.crt"]
        elasticsearch.ssl.certificate: "/usr/share/kibana/config/certs/tls.crt"
        elasticsearch.ssl.key: "/usr/share/kibana/config/certs/tls.key"
    resources:
      requests:
        cpu: "1000m"
        memory: "1Gi"
      limits:
        cpu: "1000m"
        memory: "1Gi"
