apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kibana
  namespace: system-observability
spec:
  interval: 5m
  chart:
    spec:
      chart: kibana
      # renovate: datasource=helm depName=kibana package=kibana helmRepo=https://helm.elastic.co
      version: "8.5.1"
      sourceRef:
        kind: HelmRepository
        name: elastic-kibana
        namespace: system-observability
  values:
    kibanaConfig:
      kibana.yml: |
        elasticsearch.ssl.certificateAuthorities: ["/usr/share/kibana/config/certs/ca.crt"]
        elasticsearch.ssl.certificate: "/usr/share/kibana/config/certs/tls.crt"
        elasticsearch.ssl.key: "/usr/share/kibana/config/certs/tls.key"
    resources:
      requests:
        cpu: "1000m"
        memory: "1Gi"
      limits:
        cpu: "1000m"
        memory: "1Gi"
