apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kibana
  namespace: system-observability
spec:
  interval: 5m
  chart:
    spec:
      chart: kibana
      # renovate: datasource=helm depName=kibana package=kibana helmRepo=https://helm.elastic.co
      version: "8.5.1"
      sourceRef:
        kind: HelmRepository
        name: elastic-kibana
        namespace: system-observability
  values:
    # renovate: datasource=docker depName=docker.elastic.co/kibana/kibana package=docker.elastic.co/kibana/kibana
    image: docker.elastic.co/kibana/kibana:8.19.7@sha256:8e5188f8777d873f98204220d7957f640a952c3e9b59a519c292b7ebfad7dfd3
    kibanaConfig:
      kibana.yml: |
        elasticsearch.ssl.certificateAuthorities: ["/usr/share/kibana/config/certs/ca.crt"]
        elasticsearch.ssl.certificate: "/usr/share/kibana/config/certs/tls.crt"
        elasticsearch.ssl.key: "/usr/share/kibana/config/certs/tls.key"
    resources:
      requests:
        cpu: "1000m"
        memory: "1Gi"
      limits:
        cpu: "1000m"
        memory: "1Gi"
