apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kibana
  namespace: system-observability
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: kibana
      # renovate: datasource=helm depName=kibana package=kibana helmRepo=https://helm.elastic.co
      version: "8.5.1"
      sourceRef:
        kind: HelmRepository
        name: elastic-kibana
  values:
    # renovate: datasource=docker depName=docker.elastic.co/kibana/kibana package=docker.elastic.co/kibana/kibana
    image: docker.elastic.co/kibana/kibana:9.4.0@sha256:bdf6e48cf7c86951403583e94d795f23b2c9c60a3b08218707941ee7c25eb5b8
    kibanaConfig:
      kibana.yml: |
        elasticsearch.ssl.certificateAuthorities: ["/usr/share/kibana/config/certs/ca.crt"]
        elasticsearch.ssl.certificate: "/usr/share/kibana/config/certs/tls.crt"
        elasticsearch.ssl.key: "/usr/share/kibana/config/certs/tls.key"
    resources:
      requests:
        cpu: "1000m"
        memory: "1Gi"
      limits:
        cpu: "1000m"
        memory: "1Gi"
