---
apiVersion: v1
kind: Service
metadata:
  name: ${pg_instance_name}-postgres-exporter
  namespace: system-database
spec:
  selector:
    app: ${pg_instance_name}-postgres-exporter
  ports:
    - name: metrics
      port: 9187
      targetPort: metrics
