apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - path: patches/envoy-proxy.yaml
    target:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: external
      namespace: system-gateway
