apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  labels:
    fluentbit.fluent.io/component: logging
    fluentbit.fluent.io/enabled: "true"
  name: upstream-warnings
spec:
  # Run after service-name filter (ordinal 100) since we match on service_name
  ordinal: 105
  match: kube.*
  filters:
  - lua:
      call: suppress_upstream_warnings
      script:
        key: upstream-warnings.lua
        name: fluent-bit-upstream-warnings-config
      timeAsTable: true
