apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterInput
metadata:
  labels:
    fluentbit.fluent.io/component: logging
    fluentbit.fluent.io/enabled: "true"
  name: containerd
spec:
  systemd:
    db: /fluent-bit/tail/systemd.db
    dbSync: Normal
    path: /var/log/journal
    storageType: memory
    stripUnderscores: "off"
    systemdFilter:
    - _SYSTEMD_UNIT=containerd.service
    - _SYSTEMD_UNIT=kubelet.service
    tag: service.*
