---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openbao-server
  namespace: system-secrets-store
spec:
  secretName: openbao-server-tls
  issuerRef:
    name: private
    kind: ClusterIssuer
  commonName: openbao
  dnsNames:
    - "openbao"
    - "openbao.system-secrets-store.svc.cluster.local"
    - "*.openbao.system-secrets-store.svc.cluster.local"
    - "openbao-internal"
    - "openbao-internal.system-secrets-store.svc.cluster.local"
    - "*.openbao-internal.system-secrets-store.svc.cluster.local"
  usages:
    - digital signature
    - key encipherment
    - server auth
