---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openbao
  namespace: system-secrets-store
spec:
  interval: 10m
  timeout: 3m
  url: https://openbao.github.io/openbao-helm
