---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  labels:
    fluentbit.fluent.io/component: logging
    fluentbit.fluent.io/enabled: "true"
  name: fluentd
spec:
  retry_limit: "no_limits"
  forward:
    host: fluentd.system-observability.svc.cluster.local
    port: 24224
  matchRegex: (?:kube|service)\.(.*)
