---
apiVersion: batch/v1
kind: Job
metadata:
  name: cert-init
  namespace: system-pki
  annotations:
    fluxcd.io/reconcile: "false"
  labels:
    app: cert-init
spec:
  backoffLimit: 10
  template:
    metadata:
      labels:
        app: cert-init
    spec:
      serviceAccountName: copy-root-cert
      containers:
      - name: cert-init
        # renovate: datasource=docker depName=kubectl package=alpine/k8s
        image: alpine/k8s:1.34.1
        command:
          - /bin/sh
          - -c
          - |
            set -e
            
            echo "Initializing certificate sync for trust-manager..."
            
            # Wait for secret to be available
            i=1
            while [ $i -le 30 ]; do
              if kubectl get secret private-ca-cert -n system-pki >/dev/null 2>&1; then
                echo "Secret found, proceeding with sync..."
                break
              else
                echo "Waiting for secret (attempt $i/30)..."
                sleep 10
              fi
              i=$((i + 1))
            done
            
            if [ $i -gt 30 ]; then
              echo "Failed to find secret after 30 attempts" >&2
              exit 1
            fi
            
            # Execute the shared sync script
            cp /scripts/sync.sh /tmp/sync.sh
            /tmp/sync.sh
            
            echo "Certificate sync completed successfully - trust-manager can now distribute the CA cert"
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
          readOnly: true
        - name: temp-volume
          mountPath: /tmp
      restartPolicy: OnFailure
      volumes:
      - name: script-volume
        configMap:
          name: cert-sync-script
          defaultMode: 0755
      - name: temp-volume
        emptyDir: {} 
