---
apiVersion: batch/v1
kind: Job
metadata:
  name: copy-root-cert-job
  namespace: system-pki
spec:
  backoffLimit: 10
  template:
    spec:
      containers:
      - name: copy-root-cert
        # renovate: datasource=docker depName=kubectl package=bitnami/kubectl
        image: bitnami/kubectl:1.33.2
        command:
          - /bin/sh
          - -c
          - |
            set -e

            i=1
            while [ $i -le 10 ]; do
              if kubectl get secret private-ca-cert -n system-pki; then
                kubectl get secret private-ca-cert -n system-pki -o jsonpath='{.data.ca\.crt}' | base64 --decode > /mnt/ca.crt;
                if ! kubectl get configmap private-ca-cert -n system-pki-trust >/dev/null 2>&1; then
                  kubectl create configmap private-ca-cert --from-file=ca.crt=/mnt/ca.crt -n system-pki-trust --dry-run=client -o yaml | kubectl apply -f -;
                fi;
                break;
              else
                echo "waiting for secret";
                sleep 6;
              fi;
              i=$((i + 1))
              if [ $i -gt 10 ]; then
                echo "Failed to retrieve secret after 10 attempts" >&2;
                exit 1;
              fi;
            done;
        volumeMounts:
        - name: cert-volume
          mountPath: /mnt
      restartPolicy: OnFailure
      volumes:
      - name: cert-volume
        emptyDir: {}
      serviceAccountName: copy-root-cert
