apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ca-certificate.yaml
  - ca-issuer.yaml
  - inject-private-ca-policy.yaml
  - cert-sync-script.yaml
  - cert-init.yaml
  - cert-sync.yaml
  - rbac.yaml
  - serviceaccount.yaml
  - trust-bundle.yaml
patches:
  - path: patches/cluster-issuer.yaml
