---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: private-ca
spec:
  sources:
  - useDefaultCAs: true
  - configMap:
      name: private-ca-cert
      key: ca.crt
  target:
    configMap:
      key: trust-bundle.pem
    namespaceSelector:
      matchLabels:
        use-custom-ca: "true"
