---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: system-csi
spec:
  values:
    localpv-provisioner:
      localpv:
        enabled: true
        basePath: ${local_volume_path:-/var/local}
