apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: system-observability
spec:
  interval: 5m
  timeout: 15m
  dependsOn: []
  chart:
    spec:
      chart: grafana
      # renovate: datasource=helm depName=grafana package=grafana helmRepo=https://grafana.github.io/helm-charts
      version: 10.5.15
      sourceRef:
        kind: HelmRepository
        name: grafana
  values:
    grafana.ini:
      date_formats:
        full_date: ${date_full:-YYYY-MM-DD HH:mm:ss}
        interval_second: ${date_interval_second:-HH:mm:ss}
        interval_minute: ${date_interval_minute:-HH:mm}
        interval_hour: ${date_interval_hour:-MM/DD HH:mm}
        interval_day: ${date_interval_day:-MM/DD}
        interval_month: YYYY-MM
        interval_year: YYYY
      default:
        timezone: ${timezone:-utc}
    image:
      # renovate: datasource=docker depName=grafana/grafana package=grafana/grafana
      tag: 12.4.3@sha256:2e986801428cd689c2358605289c90ab37d2b39e24808874971f54c99bcdc412
    initChownData:
      image:
        # renovate: datasource=docker depName=library/busybox package=library/busybox
        tag: 1.37.0@sha256:1487d0af5f52b4ba31c7e465126ee2123fe3f2305d638e7827681e7cf6c83d5e
    downloadDashboardsImage:
      # renovate: datasource=docker depName=curlimages/curl package=curlimages/curl
      tag: 8.19.0@sha256:9a6f6a17667960e077f1b153009aaf18ac99a622221084e1938a45a06fff057a
    sidecar:
      image:
        # renovate: datasource=docker depName=kiwigrid/k8s-sidecar package=kiwigrid/k8s-sidecar
        tag: 2.6.0@sha256:a6c101156d42ef1050c536fcbcc03bf314544a63ee2daafe45280bc8dbab398f
      dashboards:
        enabled: true
        label: grafana_dashboard
        labelValue: "1"
        folder: /var/lib/grafana/dashboards/sidecar
        folderAnnotation: grafana_folder
        provider:
          foldersFromFilesStructure: true
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers: []
    dashboards: {}
    plugins: []
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources: []
