apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: system-observability
spec:
  interval: 5m
  timeout: 15m
  dependsOn: []
  chart:
    spec:
      chart: grafana
      # renovate: datasource=helm depName=grafana package=grafana helmRepo=https://grafana.github.io/helm-charts
      version: 10.5.15
      sourceRef:
        kind: HelmRepository
        name: grafana
  values:
    grafana.ini:
      date_formats:
        full_date: ${date_full:-YYYY-MM-DD HH:mm:ss}
        interval_second: ${date_interval_second:-HH:mm:ss}
        interval_minute: ${date_interval_minute:-HH:mm}
        interval_hour: ${date_interval_hour:-MM/DD HH:mm}
        interval_day: ${date_interval_day:-MM/DD}
        interval_month: YYYY-MM
        interval_year: YYYY
      default:
        timezone: ${timezone:-utc}
    image:
      # renovate: datasource=docker depName=grafana/grafana package=grafana/grafana
      tag: 13.1.0@sha256:121a7a9ece6dc10b969f1f96eed64b4f07dfac0d0b8abc070f7cb83bbde86f63
    initChownData:
      image:
        # renovate: datasource=docker depName=library/busybox package=library/busybox
        tag: 1.38.0@sha256:fd8d9aa63ba2f0982b5304e1ee8d3b90a210bc1ffb5314d980eb6962f1a9715d
    downloadDashboardsImage:
      # renovate: datasource=docker depName=curlimages/curl package=curlimages/curl
      tag: 8.21.0@sha256:7c12af72ceb38b7432ab85e1a265cff6ae58e06f95539d539b654f2cfa64bb13
    sidecar:
      image:
        # renovate: datasource=docker depName=kiwigrid/k8s-sidecar package=kiwigrid/k8s-sidecar
        tag: 2.8.1@sha256:abb55b2165c60e8f97e473862c7a3123df6f67d44f592949577c29b8fb2df9d6
      dashboards:
        enabled: true
        label: grafana_dashboard
        labelValue: "1"
        folder: /var/lib/grafana/dashboards/sidecar
        folderAnnotation: grafana_folder
        provider:
          foldersFromFilesStructure: true
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers: []
    dashboards: {}
    plugins: []
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources: []
