---
# Pins the provider-gcp-sql pod's ServiceAccount name for Terraform's
# Workload Identity binding.
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-gcp-sql
spec:
  serviceAccountTemplate:
    metadata:
      name: provider-gcp-sql
      annotations:
        iam.gke.io/gcp-service-account: ${crossplane_gcp_service_account_email}
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          priorityClassName: windsorcli-platform-critical
          containers:
            - name: package-runtime
