{
 "title": "Cilium Operator",
 "tags": [
  "cilium",
  "networking"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage per node",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "min(irate(cilium_operator_process_cpu_seconds_total{io_cilium_app=\"operator\"}[1m])) by (pod) * 100",
     "legendFormat": "min"
    },
    {
     "expr": "avg(irate(cilium_operator_process_cpu_seconds_total{io_cilium_app=\"operator\"}[1m])) by (pod) * 100",
     "legendFormat": "avg"
    },
    {
     "expr": "max(irate(cilium_operator_process_cpu_seconds_total{io_cilium_app=\"operator\"}[1m])) by (pod) * 100",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Resident memory status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(cilium_operator_process_resident_memory_bytes{io_cilium_app=\"operator\"})",
     "legendFormat": "AVG_resident_memory_bytes"
    },
    {
     "expr": "max(cilium_operator_process_resident_memory_bytes{io_cilium_app=\"operator\"})",
     "legendFormat": "MAX_resident_memory_bytes_max"
    },
    {
     "expr": "min(cilium_operator_process_resident_memory_bytes{io_cilium_app=\"operator\"})",
     "legendFormat": "MIN_resident_memory_bytes_min"
    }
   ]
  },
  { "title": "LB IPAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "LB IP Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cilium_operator_lbipam_ips_used_total",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "LB Services",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "rate(cilium_operator_lbipam_services_matching_total[1m])",
     "legendFormat": "Matching"
    }
   ]
  },
  {
   "title": "LB IPs Available",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cilium_operator_lbipam_ips_available_total",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "LB Services Unsatisfied",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cilium_operator_lbipam_services_unsatisfied_total",
     "legendFormat": "Unsatisfied"
    }
   ]
  },
  {
   "title": "Conflicting IP Pools",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "cilium_operator_lbipam_conflicting_pools_total",
     "legendFormat": "Conflicts"
    }
   ]
  }
 ]
}