apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: filebeat
  namespace: system-telemetry
spec:
  interval: 5m
  chart:
    spec:
      chart: filebeat
      # renovate: datasource=helm depName=filebeat package=filebeat helmRepo=https://helm.elastic.co
      version: "8.5.1"
      sourceRef:
        kind: HelmRepository
        name: elastic-filebeat
        namespace: system-telemetry
  values:
    # renovate: datasource=docker depName=docker.elastic.co/beats/filebeat package=docker.elastic.co/beats/filebeat
    image: docker.elastic.co/beats/filebeat:9.2.1@sha256:def4cb8f42e49fbf43465e3ba143314e0cd773e433db6cdb10e9ac0fd383e69b
    daemonset:
      secretMounts:
        - name: filebeat-tls
          secretName: filebeat-tls
          path: /usr/share/filebeat/certs/
      extraEnvs:
        - name: ELASTICSEARCH_HOSTS
          value: "elasticsearch-master.system-observability.svc.cluster.local"
        - name: "ELASTICSEARCH_USERNAME"
          valueFrom:
            secretKeyRef:
              name: elasticsearch-master-credentials
              key: username
        - name: "ELASTICSEARCH_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: elasticsearch-master-credentials
              key: password
        - name: "ssl.certificate_authorities"
          value: "/usr/share/filebeat/certs/ca.crt"
    resources:
      requests:
        cpu: "100m"
        memory: "100M"
      limits:
        cpu: "500m"
        memory: "300M"
