---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-manager
  namespace: system-telemetry
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: secret-manager
    namespace: system-telemetry
---
apiVersion: batch/v1
kind: Job
metadata:
  name: secret-manager-init-job
  namespace: system-telemetry
spec:
  backoffLimit: 10
  template:
    spec:
      containers:
      - name: copy-k8s-secret
        image: bitnami/kubectl:1.31.2
        command: ["/bin/sh", "-c", "--"]
        args:
          - |
            kubectl get secret elasticsearch-master-credentials -n system-observability -o yaml \
              | yq eval 'del(.metadata.resourceVersion, .metadata.uid, .metadata.creationTimestamp, .metadata.managedFields) | .metadata.namespace = "system-telemetry"' - \
              | kubectl apply -n system-telemetry -f -
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
              - ALL
      restartPolicy: Never
      volumes:
        - name: temp-volume
          emptyDir: {}
      serviceAccountName: secret-manager

