---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-manager
  namespace: system-telemetry
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: secret-manager
    namespace: system-telemetry
---
apiVersion: batch/v1
kind: Job
metadata:
  name: secret-manager-init-job
  namespace: system-telemetry
  annotations:
    kustomize.toolkit.fluxcd.io/force: enabled
spec:
  backoffLimit: 10
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      containers:
      - name: copy-k8s-secret
        # renovate: datasource=docker depName=kubectl package=alpine/k8s
        image: alpine/k8s:1.35.0@sha256:18bc02c1e0df04451f4f9194eb7b7341c1165da5495459b52f85f72fb9545032
        command: ["/bin/sh", "-c", "--"]
        args:
          - |
            kubectl get secret elasticsearch-master-credentials -n system-observability -o yaml \
              | yq eval 'del(.metadata.resourceVersion, .metadata.uid, .metadata.creationTimestamp, .metadata.managedFields) | .metadata.namespace = "system-telemetry"' - \
              | kubectl apply -n system-telemetry -f -
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
              - ALL
      restartPolicy: Never
      volumes:
        - name: temp-volume
          emptyDir: {}
      serviceAccountName: secret-manager

