kind: Blueprint
apiVersion: blueprints.windsorcli.dev/v1alpha1
metadata:
  name: aws-example
  description: This blueprint outlines resources in the aws-example context
repository:
  url: https://github.com/windsorcli/core
  ref:
    branch: aws-eks
  secretName: flux-system
sources:
- name: core
  url: github.com/windsorcli/core
  ref:
    tag: v0.3.0
terraform:
- path: network/aws-vpc
- path: cluster/aws-eks
- path: gitops/flux
kustomize:
- name: telemetry-base
  path: telemetry/base
  components:
  - prometheus
  - prometheus/flux
- name: telemetry-resources
  path: telemetry/resources
  dependsOn:
  - telemetry-base
  components:
  - metrics-server
  - prometheus
  - prometheus/flux
- name: policy-base
  path: policy/base
  components:
  - kyverno
- name: policy-resources
  path: policy/resources
  dependsOn:
  - policy-base
- name: ingress-base
  path: ingress/base
  dependsOn:
  - pki-resources
  force: true
  components:
  - nginx
  - nginx/loadbalancer
  - nginx/coredns
  - nginx/flux-webhook
  - nginx/web
- name: pki-base
  path: pki/base
  dependsOn:
  - policy-resources
  force: true
  components:
  - cert-manager
  - trust-manager
- name: pki-resources
  path: pki/resources
  dependsOn:
  - pki-base
  force: true
  components:
  - private-issuer/ca
  - public-issuer/selfsigned
- name: dns
  path: dns
  dependsOn:
  - ingress-base
  - pki-base
  force: true
  components:
  - coredns
  - coredns/etcd
  - external-dns
  - external-dns/coredns
  - external-dns/ingress
- name: gitops
  path: gitops/flux
  dependsOn:
  - ingress-base
  force: true
  components:
  - webhook
- name: observability
  path: observability
  dependsOn:
  - ingress-base
  components:
  - grafana
  - grafana/ingress
  - grafana/prometheus
  - grafana/node
  - grafana/kubernetes
  - grafana/flux
