version: 0.2

phases:
  install:
    commands:
      - "curl -L -o windsor_0.5.6_linux_amd64.tar.gz https://github.com/windsorcli/cli/releases/download/v0.5.6/windsor_0.5.6_linux_amd64.tar.gz && \
        sudo tar -xzf windsor_0.5.6_linux_amd64.tar.gz -C /usr/local/bin && \
        sudo chmod +x /usr/local/bin/windsor"
      - "export HOME=$(pwd)"
      - "curl -L -o aqua_linux_amd64.tar.gz https://github.com/aquaproj/aqua/releases/download/v2.49.0-0/aqua_linux_amd64.tar.gz"
      - "mkdir -p aqua"
      - "tar -xzf aqua_linux_amd64.tar.gz -C aqua"
      - "rm aqua_linux_amd64.tar.gz"
      - "ls -la"
  pre_build:
    commands:
      - "windsor version"
  build:
    commands:
      - "export DOCKER_HOST=unix:///var/run/docker.sock"
      - "export WINDSOR_PROJECT_ROOT=$(pwd)"
      - "windsor init local"
      - "docker images"
      - "docker ps"
