version: 0.2

phases:
  install:
    commands:
      - "curl -L -o windsor_0.5.6_linux_amd64.tar.gz https://github.com/windsorcli/cli/releases/download/v0.5.6/windsor_0.5.6_linux_amd64.tar.gz && \
        sudo tar -xzf windsor_0.5.6_linux_amd64.tar.gz -C /usr/local/bin && \
        sudo chmod +x /usr/local/bin/windsor"
      - "export HOME=$(pwd)"
      - "curl -sSfL https://raw.githubusercontent.com/aquaproj/aqua-installer/v3.1.1/aqua-installer | bash"
  pre_build:
    commands:
      - "export PATH=${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin:$PATH"
      - "aqua i"
      - "windsor version"
  build:
    commands:
      - "export DOCKER_HOST=unix:///var/run/docker.sock"
      - "export WINDSOR_PROJECT_ROOT=$(pwd)"
      - "windsor init local"
      - "docker images"
      - "docker ps"
