version: "3"

vars:
  PROJECT_ROOT:
    sh: git rev-parse --show-toplevel

env:
  PRIVATE_DOMAIN_NAME: private.test
  PUBLIC_DOMAIN_NAME: public.test

includes:
  website: ./website

tasks:

  #---------------------------------------------------------------------------------------------------------------------
  # Terraform
  #---------------------------------------------------------------------------------------------------------------------

  terraform:fmt:
    desc: Runs 'terraform fmt' against all Terraform projects
    cmds:
      - terraform fmt -recursive -diff
    silent: true


  #-----------------------------------------------------------------------------------------------------------------------
  # Tests
  #-----------------------------------------------------------------------------------------------------------------------

  test:
    desc: "Run all tests"
    deps:
      - task: test:e2e

  test:e2e:
    desc: "Run tests against a specified blueprint on docker. Usage: task test"
    cmds:
      - |
        bats --show-output-of-passing-tests -t {{.PROJECT_ROOT}}/test/unit/ \
          --filter-tags baseline:full \
          --filter-tags platform:docker \
          --filter-tags security:dev \
          --filter-tags network:web \
          --filter-tags network:metal \
          --filter-tags monitoring:prometheus \
          --filter-tags monitoring:grafana \
          --filter-tags monitoring:fluent \
          --filter-tags monitoring:quickwit \
          --filter-tags network:service-mesh \
          --filter-tags network:service-mesh:kiali \
          --filter-tags gitops:flux \
          --filter-tags security:vulns

  #-----------------------------------------------------------------------------------------------------------------------
  # Dashboards
  #-----------------------------------------------------------------------------------------------------------------------

  dashboard:grafana:
    desc: "Open Grafana dashboard"
    cmds:
      - |
        open https://grafana.${PRIVATE_DOMAIN_NAME}
        kubectl get secret grafana -o jsonpath="{.data.admin-password}" -n system-observability | base64 --decode | pbcopy
        echo "Username: $(kubectl get secret grafana -o jsonpath="{.data.admin-user}" -n system-observability | base64 --decode)"
        echo "The Grafana admin password has been copied to your clipboard."
    silent: true

  dashboard:kiali:
    desc: "Open Kiali dashboard"
    cmds:
      - |
        open https://kiali.${PRIVATE_DOMAIN_NAME}
        kubectl -n network create token kiali-service-account | pbcopy
        echo "The Kiali token has been copied to your clipboard."
    silent: true

  dashboard:minio:
    desc: "Open MinIO dashboard"
    cmds:
      - |
        open https://console.minio.${PRIVATE_DOMAIN_NAME}
        kubectl -n system-object-store create token console-sa | pbcopy
        echo "The MinIO token has been copied to your clipboard."
    silent: true

  #-----------------------------------------------------------------------------------------------------------------------
  # Default (help)
  #-----------------------------------------------------------------------------------------------------------------------

  default:
    desc: "Shows help"
    cmds:
      - |
        echo "
        Usage: task [command]

        Commands:

          terraform:fmt
            Description: Runs 'terraform fmt' against all Terraform projects
            Usage: task terraform:fmt

          test
            Description: Run tests against a specified blueprint on docker
            Usage: task test

          test:charts
            Description: Run tests against helm charts
            Usage: task test:charts

          test:e2e
            Description: Run e2e tests against the local cluster
            Usage: task test:e2e
            
          dashboard:capacitor
            Description: Loads the capacitor dashboard
            Usage: task dashboard:capacitor

          dashboard:grafana
            Description: Loads the grafana dashboard and copies the password to the clipboard
            Usage: task dashboard:grafana

          dashboard:kiali
            Description: Loads the kiali dashboard
            Usage: task dashboard:kiali
        "
    silent: true
