version: '3'

tasks:
  dashboards:
    desc: Download and patch vendored assets from source.yaml files
    cmds:
      - scripts/vendor-dashboards.sh

  dashboards:lint:
    desc: Validate vendored JSON files and patch integrity
    cmds:
      - scripts/lint-dashboards.sh

  scan:
    desc: Scan for security vulnerabilities
    silent: true
    cmds:
      - cmd: source .venv/bin/activate && checkov -d {{.CLI_ARGS | default "terraform/"}} 2>/dev/null

  test:
    desc: Run all tests (Terraform and Blueprint)
    silent: true
    cmds:
      - task: test:terraform
      - task: test:blueprint

  test:terraform:
    desc: Run Terraform tests (all or specific module)
    silent: true
    cmds:
      - cmd: |
          MODULE={{.CLI_ARGS | default "terraform"}}
          if [ -d "$MODULE" ]; then
            # Create a temporary directory for test results
            TEMP_DIR=$(mktemp -d)
            # Find all test files and run them in parallel
            find "$MODULE" -type f -name '*.tftest.hcl' | while read testfile; do
              testdir=$(dirname "$testfile")
              (
                cd "$testdir" && \
                echo "Running tests in $testdir..." && \
                terraform init -input=false -reconfigure && \
                OUTPUT=$(terraform test -no-color 2>&1)
                TEST_EXIT=$?
                echo "$OUTPUT"
                if [ $TEST_EXIT -ne 0 ]; then
                  echo "FAILED: $testfile" >> "$TEMP_DIR/failures"
                fi
                # Check for warnings (case-insensitive)
                if echo "$OUTPUT" | grep -qi "Warning:"; then
                  echo "WARNINGS: $testfile" >> "$TEMP_DIR/warnings"
                fi
              ) &
            done
            # Wait for all background jobs to complete
            wait
            # Check if any tests failed
            if [ -f "$TEMP_DIR/failures" ]; then
              echo "Test failures:"
              cat "$TEMP_DIR/failures"
              rm -rf "$TEMP_DIR"
              exit 1
            fi
            # Check if any warnings were found
            if [ -f "$TEMP_DIR/warnings" ]; then
              echo "Tests completed with warnings:"
              cat "$TEMP_DIR/warnings"
              rm -rf "$TEMP_DIR"
              exit 1
            fi
            rm -rf "$TEMP_DIR"
          else
            echo "Module path '$MODULE' does not exist."
            exit 1
          fi

  test:blueprint:
    desc: Run Windsor blueprint tests
    silent: true
    cmds:
      - windsor test

  fmt:
    desc: Check Terraform formatting
    silent: true
    cmds:
      - cmd: terraform fmt -recursive

  docs:
    desc: Generate Terraform documentation
    silent: true
    cmds:
      - cmd: |
          find terraform -type d -exec test -e '{}/main.tf' -a -e '{}/variables.tf' \; -print | while read -r dir; do
            if [[ "$dir" == *"/modules/"* ]]; then
              continue
            fi
            echo "Generating docs for $dir"
            docker run --rm -v "$(pwd):/src" -w "/src/$dir" quay.io/terraform-docs/terraform-docs:0.20.0 markdown table --output-file README.md --output-mode inject .
          done
