apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cluster-autoscaler
  namespace: system-compute
spec:
  interval: 10m
  timeout: 3m
  url: https://kubernetes.github.io/autoscaler
