---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: system-pki
spec:
  interval: 5m
  timeout: 20m
  chart:
    spec:
      chart: cert-manager
      # renovate: datasource=helm depName=cert-manager package=cert-manager helmRepo=https://charts.jetstack.io
      version: 1.21.0
      sourceRef: 
        kind: HelmRepository
        name: jetstack
  values:
    image:
      # renovate: datasource=docker depName=quay.io/jetstack/cert-manager-controller package=quay.io/jetstack/cert-manager-controller
      tag: v1.21.0@sha256:e370f7800a53078e9d74324287a7d52b553864e55f5b4e521f911c3f6c7da203
    webhook:
      image:
        # renovate: datasource=docker depName=quay.io/jetstack/cert-manager-webhook package=quay.io/jetstack/cert-manager-webhook
        tag: v1.21.0@sha256:c33cca307541e2d58861a55b1af5f390b7e19c8741e48b433693b73a7cce88b3
    cainjector:
      image:
        # renovate: datasource=docker depName=quay.io/jetstack/cert-manager-cainjector package=quay.io/jetstack/cert-manager-cainjector
        tag: v1.21.0@sha256:ad1dcc5b2fccc420f9b3fbee7ce8a869450c540fd4f2f41de2d95b1ca0c4d701
    startupapicheck:
      image:
        # renovate: datasource=docker depName=quay.io/jetstack/cert-manager-startupapicheck package=quay.io/jetstack/cert-manager-startupapicheck
        tag: v1.21.0@sha256:68b3c5029dc63e64a6b6435337d7dc0eb169f889a48a02d999d1f22f31865b33
    crds:
      enabled: false
