---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: system-csi
spec:
  interval: 5m
  timeout: 5m
  chart:
    spec:
      chart: openebs
      # renovate: datasource=helm depName=openebs package=openebs helmRepo=https://openebs.github.io/openebs
      version: 4.3.3
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: system-gitops
  values:
    localpv-provisioner:
      enabled: false
      localpv:
        image:
          # renovate: datasource=docker depName=openebs/provisioner-localpv package=openebs/provisioner-localpv
          tag: 4.4.0@sha256:a9f0aa574700379fd56f7597be4493fab1bd2423e8a5eaca4eeafd377763e9df
      helperPod:
        image:
          # renovate: datasource=docker depName=openebs/linux-utils package=openebs/linux-utils
          tag: 4.1.0@sha256:f085850f69fdb278416d353a1bc1174613251ca9c471f5acd0e627eeb43e5d9e
      hostpathClass:
        enabled: false
    zfs-localpv:
      enabled: false
      zfsPlugin:
        image:
          # renovate: datasource=docker depName=openebs/zfs-driver package=openebs/zfs-driver
          tag: 2.9.0@sha256:66535204312df4f91fab45fe5cf7770b5aaf5203343220ab8f97c81645aa85cd
    lvm-localpv:
      enabled: false
      lvmPlugin:
        image:
          # renovate: datasource=docker depName=openebs/lvm-driver package=openebs/lvm-driver
          tag: 1.8.0@sha256:e3b4bbff2d084dced44945e0b15b4451714f7eb535d0f35f79afdbecaa4942e9
    mayastor:
      enabled: false
      image:
        # renovate: datasource=docker depName=openebs/mayastor-io-engine package=openebs/mayastor-io-engine
        tag: v2.9.3@sha256:c0ed974eef65e6001e75c510bf9b33c27f086097f90edbebc4ae969f5e780a21
      base:
        metrics:
          enabled: false
    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: false
    loki:
      enabled: false
    minio:
      enabled: false
    alloy:
      enabled: false
    preUpgradeHook:
      image:
        # renovate: datasource=docker depName=openebs/kubectl package=openebs/kubectl
        tag: 1.25.15@sha256:7a8d6955f40da47707896368ec4e7f9029ca643986af4ebcf4cbeb7798f0f896
