---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: openebs
  namespace: system-gitops
spec:
  interval: 10m
  timeout: 5m
  url: https://openebs.github.io/openebs
