---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
  namespace: system-csi
spec:
  interval: 5m
  timeout: 5m
  chart:
    spec:
      chart: openebs
      # renovate: datasource=helm depName=openebs package=openebs helmRepo=https://openebs.github.io/openebs
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: system-gitops
  values:
    localpv-provisioner:
      localpv:
        enabled: false
      hostpathClass:
        enabled: false
    zfs-localpv:
      enabled: false
    lvm-localpv:
      enabled: false
    mayastor:
      enabled: false
      base:
        metrics:
          enabled: false
    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: false
