---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: system-dns
spec:
  interval: 5m
  timeout: 10m
  dependsOn: []
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: external-dns
      # renovate: datasource=helm depName=external-dns package=external-dns helmRepo=https://kubernetes-sigs.github.io/external-dns/
      version: 1.21.1
      sourceRef: 
        kind: HelmRepository
        name: external-dns
  values:
    priorityClassName: windsorcli-platform-critical
    image:
      # renovate: datasource=docker depName=registry.k8s.io/external-dns/external-dns package=registry.k8s.io/external-dns/external-dns
      tag: v0.22.0@sha256:5fdcaf7deb5c158f93a1fc6fe169cdff4cfb9ae0172bee1a90ab0ef74fb9c9cf
    env: []
    extraVolumes: []
    extraVolumeMounts: []
    triggerLoopOnEvent: true
    sources:
      - ingress
    domainFilters:
      - "${external_domain:-test}"
