apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  labels:
    fluentbit.fluent.io/component: logging
    fluentbit.fluent.io/enabled: "true"
  name: klog
spec:
  ordinal: 20
  match: kube.*
  filters:
  - lua:
      call: parse_klog
      script:
        key: klog.lua
        name: fluent-bit-klog-config
      timeAsTable: true
