apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ${gateway_name}
  namespace: system-gateway
spec:
  infrastructure:
    annotations:
      lbipam.cilium.io/sharing-key: ${gateway_name}
      lbipam.cilium.io/sharing-cross-namespace: "*"
