apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# Cloud SQL's own ProviderConfig, project policy, and tagging policy.

resources:
  - provider-config.yaml
  - project-policy.yaml
  - tag-policy.yaml
