apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: system-observability
spec:
  values:
    dashboards:
      grafana-dashboards-node:
        node-exporter-full:
          url: https://raw.githubusercontent.com/rfmoz/grafana-dashboards/d33a10c268e5081aa5de33ec8ffdfb2741109498/prometheus/node-exporter-full.json
          token: ''