apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: system-observability
spec:
  values:
    sidecar:
      dashboards:
        enabled: true
        provider:
          folder: "Node"
