{
 "title": "Global Ratelimit",
 "description": "Envoy Gateway monitoring Dashboard with exported metrics.",
 "tags": [ "Control Plane" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(watchable_depth,namespace)"
    }
   },
   {
    "name": "Runner",
    "query": {
     "query": "label_values(watchable_depth,runner)"
    }
   },
   { "name": "DefaultDomain", "query": "default/eg/http" }
  ]
 },
 "panels": [
  { "title": "Global Ratelimit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Fraction",
   "type": "timeseries",
   "description": "The fraction of this program's available CPU time used by the GC since the program started.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "miu" } },
   "targets": [
    {
     "expr": "(go_memstats_gc_cpu_fraction)*1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "gauge",
   "description": "Resident memory size",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(process_resident_memory_bytes{app_kubernetes_io_component=\"ratelimit\"})/1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "gauge",
   "description": "Virtual memory size",
   "gridPos": { "h": 7, "w": 7, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(process_virtual_memory_bytes{app_kubernetes_io_component=\"ratelimit\"})/1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Hits",
   "type": "stat",
   "description": "Number of ratelimit rule hits in total",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ratelimit_service_rate_limit_total_hits{domain=\"$DefaultDomain\", key1=\"httproute/default/http-ratelimit/rule/0/match/0/ratelimit_example_httproute/default/http-ratelimit/rule/0/match/0/ratelimit_example\", key2=\"rule-0-match-0_rule-0-match-0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Near Limit",
   "type": "stat",
   "description": "Number of rule hits over the NearLimit ratio threshold (currently 80%) but under the threshold rate.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ratelimit_service_rate_limit_near_limit{domain=\"$DefaultDomain\", key1=\"httproute/default/http-ratelimit/rule/0/match/0/ratelimit_example_httproute/default/http-ratelimit/rule/0/match/0/ratelimit_example\", key2=\"rule-0-match-0_rule-0-match-0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Over Limit",
   "type": "stat",
   "description": "Number of rule hits exceeding the threshold rate",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ratelimit_service_rate_limit_over_limit{domain=\"$DefaultDomain\", key1=\"httproute/default/http-ratelimit/rule/0/match/0/ratelimit_example_httproute/default/http-ratelimit/rule/0/match/0/ratelimit_example\", key2=\"rule-0-match-0_rule-0-match-0\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}