---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: envoyproxy
  namespace: system-gitops
spec:
  interval: 10m
  timeout: 3m
  type: ${helm_repo_type:=oci}
  url: ${helm_registry:=oci://docker.io/envoyproxy}
  insecure: ${helm_repo_insecure:=false}
