apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: system-object-store
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: operator
      # renovate: datasource=helm depName=minio-operator package=operator helmRepo=https://operator.min.io
      version: 7.1.1
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: system-gitops
  values:
    operator:
      image:
        # renovate: datasource=docker depName=minio/operator package=minio/operator
        tag: v7.1.1@sha256:cd587f60c43dab75799370ad7b6c55f53cfa2188e85f4c5eda939591f8769f47
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      additionalLabels:
        use-custom-ca: "true"
