---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-peer
  namespace: system-dns
spec:
  secretName: etcd-peer-tls
  issuerRef:
    name: private
    kind: ClusterIssuer
  commonName: etcd-peer
  dnsNames:
    - "etcd.system-dns.svc.${CLUSTER_DOMAIN:-cluster.local}"
    - "*.etcd.system-dns.svc.${CLUSTER_DOMAIN:-cluster.local}"
    - "etcd-headless.system-dns.svc.${CLUSTER_DOMAIN:-cluster.local}"
    - "*.etcd-headless.system-dns.svc.${CLUSTER_DOMAIN:-cluster.local}"
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-server
  namespace: system-dns
spec:
  secretName: etcd-server-tls
  issuerRef:
    name: private
    kind: ClusterIssuer
  commonName: etcd
  dnsNames:
    - "etcd.system-dns.svc.${CLUSTER_DOMAIN:-cluster.local}"
    - "*.etcd.system-dns.svc.${CLUSTER_DOMAIN:-cluster.local}"
    - "etcd-headless.system-dns.svc.${CLUSTER_DOMAIN:-cluster.local}"
    - "*.etcd-headless.system-dns.svc.${CLUSTER_DOMAIN:-cluster.local}"
  usages:
    - server auth
    - client auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-client
  namespace: system-dns
spec:
  secretName: etcd-client-tls
  issuerRef:
    name: private
    kind: ClusterIssuer
  commonName: etcd-client
  usages:
    - client auth
