---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: coredns-etcd-bitnami
  namespace: system-gitops
spec:
  interval: 10m
  timeout: 3m
  url: https://charts.bitnami.com/bitnami
