apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - certificates.yaml
  - helm-repository.yaml
  - helm-release.yaml
patches:
  - path: patches/patch.yaml
    target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: coredns
      namespace: system-dns
  - path: patches/helm-release.yaml
