apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - statefulset.yaml
  - service.yaml
  - certificates.yaml
  - rbac.yaml
  - network-policy.yaml
patches:
  - path: patches/helm-release.yaml
