---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: etcd
  namespace: system-dns
spec:
  podSelector:
    matchLabels:
      app: etcd
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow etcd peer communication
  - from:
    - podSelector:
        matchLabels:
          app: etcd
    ports:
    - port: 2380
      protocol: TCP
  # Allow CoreDNS to connect to etcd client endpoint
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: coredns
    ports:
    - port: 2379
      protocol: TCP
  # Allow external-dns to connect to etcd client endpoint
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: external-dns
    ports:
    - port: 2379
      protocol: TCP
  egress:
  # Allow DNS resolution
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
  # Allow etcd peer communication
  - ports:
    - port: 2380
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          app: etcd
  # Allow etcd client communication (for cluster operations)
  - ports:
    - port: 2379
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          app: etcd
