---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: etcd
  namespace: system-dns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: etcd
  namespace: system-dns
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: etcd
  namespace: system-dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: etcd
subjects:
- kind: ServiceAccount
  name: etcd
  namespace: system-dns
