---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluent-operator-config
  namespace: system-observability
spec:
  interval: 5m
  timeout: 20m
  chart:
    spec:
      chart: charts/fluent-operator
      # chart: fluent-operator
      # renovate: datasource=helm depName=fluent-operator package=fluent-operator helmRepo=https://fluent.github.io/helm-charts
      version: 4.1.0
      sourceRef:
        kind: GitRepository
        name: fluent-operator
        namespace: system-gitops
  values:
    image:
      # renovate: datasource=docker depName=ghcr.io/fluent/fluent-operator/fluent-operator package=ghcr.io/fluent/fluent-operator/fluent-operator
      tag: 3.9.0@sha256:705375468232d8d39d47c60d55296b1587501fc1cb4f2f313e7e7b4ad82cc3ed
    containerRuntime: containerd
    fluentd:
      image:
        # renovate: datasource=docker depName=ghcr.io/fluent/fluent-operator/fluentd package=ghcr.io/fluent/fluent-operator/fluentd
        tag: v1.19.2@sha256:fef9f961b919a56c7f11b0d6edcd55693150cc72d9728aac4b7a95937336774f
      enable: true
      crdsEnable: false
    fluentbit:
      image:
        # renovate: datasource=docker depName=ghcr.io/fluent/fluent-operator/fluent-bit package=ghcr.io/fluent/fluent-operator/fluent-bit
        tag: v5.0.8@sha256:edc2fb5265a7ddbd8f522b7cf0fe2358a6e968585d29b67db703d7c2e4a31d2b
      enable: true
      crdsEnable: false
