---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluent-operator-config
  namespace: system-observability
spec:
  interval: 5m
  timeout: 5m
  chart:
    spec:
      chart: charts/fluent-operator
      # chart: fluent-operator
      # renovate: datasource=helm depName=fluent-operator package=fluent-operator helmRepo=https://fluent.github.io/helm-charts
      version: 3.4.2
      sourceRef:
        kind: GitRepository
        name: fluent-operator
        namespace: system-gitops
  values:
    containerRuntime: containerd
    fluentd:
      enable: true
      crdsEnable: false
    fluentbit:
      enable: true
      crdsEnable: false
