---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluent-operator-config
  namespace: system-observability
spec:
  interval: 5m
  timeout: 20m
  chart:
    spec:
      chart: charts/fluent-operator
      # chart: fluent-operator
      # renovate: datasource=helm depName=fluent-operator package=fluent-operator helmRepo=https://fluent.github.io/helm-charts
      version: 3.5.0
      sourceRef:
        kind: GitRepository
        name: fluent-operator
        namespace: system-gitops
  values:
    image:
      # renovate: datasource=docker depName=ghcr.io/fluent/fluent-operator/fluent-operator package=ghcr.io/fluent/fluent-operator/fluent-operator
      tag: v3.7.0@sha256:680714f4eccfe174305bfd187d4f7ba5c6aa24b8ce952807343c39a92d56bbed
    containerRuntime: containerd
    fluentd:
      image:
        # renovate: datasource=docker depName=ghcr.io/fluent/fluent-operator/fluentd package=ghcr.io/fluent/fluent-operator/fluentd
        tag: v1.19.2@sha256:fef9f961b919a56c7f11b0d6edcd55693150cc72d9728aac4b7a95937336774f
      enable: true
      crdsEnable: false
    fluentbit:
      image:
        # renovate: datasource=docker depName=ghcr.io/fluent/fluent-operator/fluent-bit package=ghcr.io/fluent/fluent-operator/fluent-bit
        tag: v5.0.2@sha256:22f85d7d3c3b54539acdee08725440ffce1e974abc09fd005d058774c9f4d7cc
      enable: true
      crdsEnable: false
