formatter: markdown table

recursive:
  enabled: true
  path: .
  include-main: true

sections:
  show:
    - requirements
    - providers
    - inputs
    - outputs
    - resources

content: |-
  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: "README.md"
  mode: inject

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true 
