apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: system-telemetry
spec:
  interval: 5m
  timeout: 5m
  chart:
    spec:
      chart: metrics-server
      # renovate: datasource=helm depName=metrics-server package=metrics-server helmRepo=https://kubernetes-sigs.github.io/metrics-server/
      version: 3.12.1
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: system-gitops
