kind: Blueprint
apiVersion: blueprints.windsorcli.dev/v1alpha1
metadata:
  name: local
  description: This blueprint outlines resources in the local context
repository:
  url: http://git.test/git/telemetry-test
  ref:
    branch: main
  secretName: flux-system
sources:
- name: core
  url: github.com/windsorcli/core
  ref:
    tag: v0.2.0
terraform:
- source: core
  path: cluster/talos
- source: core
  path: gitops/flux
kustomize:
- name: policy-base
  path: policy/base
  source: core
  components:
  - kyverno
- name: policy-resources
  path: policy/resources
  source: core
  dependsOn:
  - policy-base
- name: csi
  path: csi
  source: core
  dependsOn:
  - policy-resources
  force: true
  components:
  - openebs
  - openebs/dynamic-localpv
- name: ingress-base
  path: ingress/base
  source: core
  dependsOn:
  - pki-resources
  force: true
  components:
  - nginx
  - nginx/nodeport
  - nginx/coredns
  - nginx/flux-webhook
  - nginx/web
- name: pki-base
  path: pki/base
  source: core
  dependsOn:
  - policy-resources
  force: true
  components:
  - cert-manager
  - trust-manager
- name: pki-resources
  path: pki/resources
  source: core
  dependsOn:
  - pki-base
  force: true
  components:
  - private-issuer/ca
  - public-issuer/selfsigned
- name: dns
  path: dns
  source: core
  dependsOn:
  - ingress-base
  - pki-base
  force: true
  components:
  - coredns
  - coredns/etcd
  - external-dns
  - external-dns/localhost
  - external-dns/coredns
  - external-dns/ingress
- name: gitops
  path: gitops/flux
  source: core
  dependsOn:
  - ingress-base
  force: true
  components:
  - webhook
- name: demo
  path: demo/bookinfo
  source: core
  dependsOn:
  - ingress-base
  force: true
  components:
  - ingress
- name: fluentbit
  path: telemetry/base
  components:
  - fluentbit
- name: fluentbit-resources
  path: telemetry/resources
  components:
  - fluentbit
- name: metrics-server-resources
  path: telemetry/resources
  components:
  - metrics-server
- name: object-store-base
  path: object-store/base
  components:
  - minio
- name: object-store-resources
  path: object-store/resources
  dependsOn:
  - object-store-base
  components:
  - minio
- name: observability-base
  path: observability/base
- name: quickwit
  path: observability/quickwit
  dependsOn:
  - observability-base
  - pki-base
  - object-store-resources
  components:
  - minio
