kind: Blueprint
apiVersion: blueprints.windsorcli.dev/v1alpha1
metadata:
  name: local
  description: This blueprint outlines resources in the local context
sources:
- name: core
  url: github.com/windsorcli/core
  ref: v0.1.0
terraform:
- source: core
  path: cluster/talos
