services:
  controlplane-1.test:
    container_name: controlplane-1.test
    environment:
      PLATFORM: container
      TALOSSKU: 2CPU-2048RAM
    hostname: controlplane-1.test
    image: ghcr.io/siderolabs/talos:v1.9.1
    networks:
      windsor-local:
        ipv4_address: 10.5.0.2
    privileged: true
    read_only: true
    restart: always
    security_opt:
      - seccomp=unconfined
    tmpfs:
      - /run
      - /system
      - /tmp
    volumes:
      - type: volume
        source: controlplane_1_system_state
        target: /system/state
      - type: volume
        source: controlplane_1_var
        target: /var
      - type: volume
        source: controlplane_1_etc_cni
        target: /etc/cni
      - type: volume
        source: controlplane_1_etc_kubernetes
        target: /etc/kubernetes
      - type: volume
        source: controlplane_1_usr_libexec_kubernetes
        target: /usr/libexec/kubernetes
      - type: volume
        source: controlplane_1_opt
        target: /opt
  dns.test:
    command:
      - -conf
      - /etc/coredns/Corefile
    container_name: dns.test
    image: coredns/coredns:1.11.3
    labels:
      context: local
      managed_by: windsor
      role: dns
    networks:
      windsor-local:
        ipv4_address: 10.5.0.3
    restart: always
    volumes:
      - type: bind
        source: ./Corefile
        target: /etc/coredns/Corefile
  gcr.test:
    container_name: gcr.test
    environment:
      REGISTRY_PROXY_REMOTEURL: https://gcr.io
    image: registry:2.8.3
    labels:
      context: local
      managed_by: windsor
      role: registry
    networks:
      windsor-local:
        ipv4_address: 10.5.0.4
    restart: always
    volumes:
      - type: bind
        source: /Users/ryanvangundy/Developer/windsorcli/core/.docker-cache
        target: /var/lib/registry
  ghcr.test:
    container_name: ghcr.test
    environment:
      REGISTRY_PROXY_REMOTEURL: https://ghcr.io
    image: registry:2.8.3
    labels:
      context: local
      managed_by: windsor
      role: registry
    networks:
      windsor-local:
        ipv4_address: 10.5.0.5
    restart: always
    volumes:
      - type: bind
        source: /Users/ryanvangundy/Developer/windsorcli/core/.docker-cache
        target: /var/lib/registry
  git.test:
    container_name: git.test
    environment:
      GIT_PASSWORD: local
      GIT_USERNAME: local
      RSYNC_EXCLUDE: .docker-cache,.terraform,data,.volumes,.tf_modules,.venv
      RSYNC_PROTECT: flux-system
      VERIFY_SSL: "false"
      WEBHOOK_URL: http://flux-webhook.private.test
    image: ghcr.io/windsorcli/git-livereload-server:v0.2.1
    labels:
      context: local
      managed_by: windsor
      role: git-repository
    networks:
      windsor-local:
        ipv4_address: 10.5.0.6
    restart: always
    volumes:
      - type: bind
        source: ${WINDSOR_PROJECT_ROOT}
        target: /repos/mount/core
  quay.test:
    container_name: quay.test
    environment:
      REGISTRY_PROXY_REMOTEURL: https://quay.io
    image: registry:2.8.3
    labels:
      context: local
      managed_by: windsor
      role: registry
    networks:
      windsor-local:
        ipv4_address: 10.5.0.7
    restart: always
    volumes:
      - type: bind
        source: /Users/ryanvangundy/Developer/windsorcli/core/.docker-cache
        target: /var/lib/registry
  registry-1.docker.test:
    container_name: registry-1.docker.test
    environment:
      REGISTRY_PROXY_LOCALURL: https://docker.io
      REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io
    image: registry:2.8.3
    labels:
      context: local
      managed_by: windsor
      role: registry
    networks:
      windsor-local:
        ipv4_address: 10.5.0.9
    restart: always
    volumes:
      - type: bind
        source: /Users/ryanvangundy/Developer/windsorcli/core/.docker-cache
        target: /var/lib/registry
  registry.k8s.test:
    container_name: registry.k8s.test
    environment:
      REGISTRY_PROXY_REMOTEURL: https://registry.k8s.io
    image: registry:2.8.3
    labels:
      context: local
      managed_by: windsor
      role: registry
    networks:
      windsor-local:
        ipv4_address: 10.5.0.10
    restart: always
    volumes:
      - type: bind
        source: /Users/ryanvangundy/Developer/windsorcli/core/.docker-cache
        target: /var/lib/registry
  registry.test:
    container_name: registry.test
    image: registry:2.8.3
    labels:
      context: local
      managed_by: windsor
      role: registry
    networks:
      windsor-local:
        ipv4_address: 10.5.0.8
    restart: always
    volumes:
      - type: bind
        source: /Users/ryanvangundy/Developer/windsorcli/core/.docker-cache
        target: /var/lib/registry
  worker-1.test:
    container_name: worker-1.test
    environment:
      PLATFORM: container
      TALOSSKU: 4CPU-4096RAM
    hostname: worker-1.test
    image: ghcr.io/siderolabs/talos:v1.9.1
    networks:
      windsor-local:
        ipv4_address: 10.5.0.11
    privileged: true
    read_only: true
    restart: always
    security_opt:
      - seccomp=unconfined
    tmpfs:
      - /run
      - /system
      - /tmp
    volumes:
      - type: volume
        source: worker_1_system_state
        target: /system/state
      - type: volume
        source: worker_1_var
        target: /var
      - type: volume
        source: worker_1_etc_cni
        target: /etc/cni
      - type: volume
        source: worker_1_etc_kubernetes
        target: /etc/kubernetes
      - type: volume
        source: worker_1_usr_libexec_kubernetes
        target: /usr/libexec/kubernetes
      - type: volume
        source: worker_1_opt
        target: /opt
      - type: bind
        source: ${WINDSOR_PROJECT_ROOT}/.volumes
        target: /var/local
networks:
  windsor-local:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16
volumes:
  controlplane_1_etc_cni: {}
  controlplane_1_etc_kubernetes: {}
  controlplane_1_opt: {}
  controlplane_1_system_state: {}
  controlplane_1_usr_libexec_kubernetes: {}
  controlplane_1_var: {}
  worker_1_etc_cni: {}
  worker_1_etc_kubernetes: {}
  worker_1_opt: {}
  worker_1_system_state: {}
  worker_1_usr_libexec_kubernetes: {}
  worker_1_var: {}
