kind: Blueprint
apiVersion: blueprints.windsorcli.dev/v1alpha1
metadata:
  name: colima
  description: This blueprint configures core for running in a Colima managed VM
repository:
  url: http://git.test/git/core
  ref:
    branch: main
  secretName: flux-system
sources:
- name: core
  url: github.com/windsorcli/core
  ref:
    branch: main
terraform:
- path: cluster/talos
- path: gitops/flux
kustomize:
- name: policy-base
  path: policy/base
  components:
  - kyverno
- name: policy-resources
  path: policy/resources
  dependsOn:
  - policy-base
- name: pki-base
  path: pki/base
  dependsOn:
  - policy-resources
  force: true
  components:
  - cert-manager
  - trust-manager
- name: pki-resources
  path: pki/resources
  dependsOn:
  - pki-base
  force: true
  components:
  - private-issuer/ca
  - public-issuer/selfsigned
- name: dns
  path: dns
  dependsOn:
  - pki-base
  force: true
  components:
  - coredns
  - coredns/etcd
  - external-dns
  - external-dns/coredns
  - external-dns/ingress
- name: lb-base
  path: lb/base
  dependsOn:
  - policy-resources
  force: true
  components:
  - metallb
- name: lb-resources
  path: lb/resources
  dependsOn:
  - lb-base
  force: true
  components:
  - metallb/layer2
- name: ingress-base
  path: ingress/base
  dependsOn:
  - pki-resources
  force: true
  components:
  - nginx
  - nginx/loadbalancer
  - nginx/coredns
  - nginx/flux-webhook
  - nginx/web
- name: gitops
  path: gitops/flux
  dependsOn:
  - ingress-base
  force: true
  components:
  - webhook
