apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: system-lb
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: metallb
      # renovate: datasource=helm depName=metallb package=metallb helmRepo=https://metallb.github.io/metallb
      version: 0.16.1
      sourceRef:
        kind: HelmRepository
        name: metallb
  values:
    controller:
      image:
        # renovate: datasource=docker depName=quay.io/metallb/controller package=quay.io/metallb/controller
        tag: v0.16.1@sha256:f51ab515de9ccd20dc3dccb093e48df8adddac019326c456f449e55ba91b6420
    speaker:
      image:
        # renovate: datasource=docker depName=quay.io/metallb/speaker package=quay.io/metallb/speaker
        tag: v0.16.1@sha256:16561e96531e1852d5c229ad7fae6e994dcfa983ff7f4de6b6208b34a4e2ddbc
      frr:
        image:
          # renovate: datasource=docker depName=quay.io/frrouting/frr package=quay.io/frrouting/frr
          tag: 10.7.0@sha256:65e5967b922572c0565d968388fb06af69d7e9b3b3eea40ad7e3810687667f68
