apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: resource-limits-requests
spec:
  validationFailureAction: Audit
  background: false
  rules:
    - name: check-resource-limits-requests
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - "system-*"
          - resources:
              kinds:
                - Pod
              namespaceSelector:
                matchLabels:
                  policy.windsorcli.dev/managed: "true"
      exclude:
        any:
          - resources:
              kinds:
                - Pod
              namespaceSelector:
                matchLabels:
                  policy.windsorcli.dev/managed: "false"
      preconditions:
        all:
          - key: "{{request.namespace}}"
            operator: NotEquals
            value: "kube-system"
      validate:
        message: "Resource limits and requests must be set on all containers."
        anyPattern:
          - spec:
              containers:
                - resources:
                    requests:
                      memory: "?*"
                      cpu: "?*"
                    limits:
                      memory: "?*"

