kind: Facet
apiVersion: blueprints.windsorcli.dev/v1alpha1
metadata:
  name: observability
  description: Observability stack with multiple log storage drivers

when: addons?.observability?.enabled == true || dev == true

kustomize:

# Dashboards
- name: observability
  path: observability
  timeout: 15m
  interval: 10m
  dependsOn:
    - ingress
  components:
    - grafana
    - grafana/ingress
    - grafana/prometheus
    - grafana/dashboards/node
    - grafana/dashboards/kubernetes
    - grafana/dashboards/flux
    - grafana/dashboards/cert-manager
    - grafana/dashboards/nginx
  substitutions:
    external_domain: "${dns?.domain}"
    timezone: "${timezone}"
    date_full: "${time_format == '12h' ? 'MMM DD, YYYY @ hh:mm:ss a' : 'YYYY-MM-DD HH:mm:ss'}"
    date_interval_second: "${time_format == '12h' ? 'hh:mm:ss a' : 'HH:mm:ss'}"
    date_interval_minute: "${time_format == '12h' ? 'hh:mm a' : 'HH:mm'}"
    date_interval_hour: "${time_format == '12h' ? 'MMM DD hh:mm a' : 'MM/DD HH:mm'}"
    date_interval_day: "${time_format == '12h' ? 'MMM DD' : 'MM/DD'}"

# FluentD outputs
- name: observability
  path: observability
  when: addons?.observability?.logs_driver == 'stdout'
  dependsOn:
    - telemetry-resources
  components:
    - fluentd
    - fluentd/filters/otel
    - fluentd/outputs/stdout

# Quickwit log storage
- name: observability
  path: observability
  when: addons?.observability?.logs_driver == 'quickwit'
  dependsOn:
    - csi
    - telemetry-resources
  components:
    - fluentd
    - fluentd/filters/otel
    - fluentd/outputs/quickwit
    - quickwit
    - quickwit/pvc
    - quickwit/prometheus
    - grafana/quickwit

# Elasticsearch + Kibana
- name: observability
  path: observability
  when: addons?.observability?.logs_driver == 'elasticsearch'
  dependsOn:
    - csi
    - ingress
  components:
    - elasticsearch
    - kibana
    - kibana/ingress
  substitutions:
    external_domain: ${dns?.domain}

# Elasticsearch telemetry
- name: telemetry-base
  path: telemetry/base
  when: addons?.observability?.logs_driver == 'elasticsearch'
  timeout: 30m
  interval: 10m
  strategy: replace
  components:
    - prometheus
    - prometheus/flux
    - filebeat

- name: telemetry-resources
  path: telemetry/resources
  when: addons?.observability?.logs_driver == 'elasticsearch'
  timeout: 10m
  interval: 5m
  strategy: replace
  dependsOn:
    - telemetry-base
  components:
    - metrics-server
    - prometheus
    - prometheus/flux
