kind: Facet
apiVersion: blueprints.windsorcli.dev/v1alpha1
metadata:
  name: observability
  description: Observability stack with metrics backends, log storage drivers, and dashboarding

when: addons.observability.enabled == true || dev == true

kustomize:

# Grafana dashboards (self-hosted Grafana, typically used with prometheus metrics)
- name: observability
  path: observability
  when: (addons.observability.dashboards ?? 'grafana') == 'grafana'
  timeout: 15m
  interval: 10m
  components:
    - grafana
    - grafana/prometheus
    - grafana/dashboards/node
    - grafana/dashboards/kubernetes
    - grafana/dashboards/flux
    - grafana/dashboards/cert-manager
    - grafana/dashboards/nginx
  substitutions:
    external_domain: ${dns.domain}
    timezone: ${timezone}
    date_full: "${time_format == '12h' ? 'MMM DD, YYYY @ hh:mm:ss a' : 'YYYY-MM-DD HH:mm:ss'}"
    date_interval_second: "${time_format == '12h' ? 'hh:mm:ss a' : 'HH:mm:ss'}"
    date_interval_minute: "${time_format == '12h' ? 'hh:mm a' : 'HH:mm'}"
    date_interval_hour: "${time_format == '12h' ? 'MMM DD hh:mm a' : 'MM/DD HH:mm'}"
    date_interval_day: "${time_format == '12h' ? 'MMM DD' : 'MM/DD'}"

# Grafana ingress (only when ingress is enabled)
- name: observability
  path: observability
  when: (addons.observability.dashboards ?? 'grafana') == 'grafana' && ingress.enabled == true
  dependsOn:
    - ingress
  components:
    - grafana/ingress

# FluentD stdout output
- name: observability
  path: observability
  when: addons.observability.logs_driver == 'stdout'
  dependsOn:
    - telemetry-resources
  components:
    - fluentd/outputs/stdout

# Quickwit log storage
- name: observability
  path: observability
  when: addons.observability.logs_driver == 'quickwit'
  dependsOn:
    - csi
    - telemetry-resources
  components:
    - fluentd/outputs/quickwit
    - quickwit
    - quickwit/pvc
    - quickwit/prometheus
    - "${(addons.observability.dashboards ?? 'grafana') == 'grafana' ? 'grafana/quickwit' : ''}"
    - "${(addons.observability.dashboards ?? 'grafana') == 'grafana' ? 'grafana/dashboards/logs/quickwit' : ''}"

# Elasticsearch + Kibana
- name: observability
  path: observability
  when: addons.observability.logs_driver == 'elasticsearch'
  dependsOn:
    - csi
    - ingress
  components:
    - elasticsearch
    - kibana
    - kibana/ingress
  substitutions:
    external_domain: ${dns.domain}

# Elasticsearch telemetry (filebeat driver)
- name: telemetry-base
  path: telemetry/base
  when: addons.observability.logs_driver == 'elasticsearch'
  timeout: 30m
  interval: 10m
  strategy: replace
  components:
    - prometheus
    - prometheus/flux
    - filebeat

- name: telemetry-resources
  path: telemetry/resources
  when: addons.observability.logs_driver == 'elasticsearch'
  timeout: 10m
  interval: 5m
  strategy: replace
  dependsOn:
    - telemetry-base
  components:
    - metrics-server
    - prometheus
    - prometheus/flux
