kind: Facet
apiVersion: blueprints.windsorcli.dev/v1alpha1
metadata:
  name: local-dev
  description: Local development overrides for VM environments

when: dev == true

terraform:
- name: gitops
  path: gitops/flux
  inputs:
    git_username: ${git.livereload.username ?? ""}
    git_password: ${git.livereload.password ?? ""}
    webhook_token: abcdef123456
    concurrency: ${max(2, min(floor((cluster.controlplanes.cpu ?? 4) / 2), floor((cluster.controlplanes.memory ?? 4) / 2), 10))}

kustomize:
- name: pki-resources
  path: pki/resources
  dependsOn:
  - pki-base
  components:
  - public-issuer/selfsigned

# Grafana dev credentials
- name: observability
  path: observability
  components:
  - grafana/dev
  substitutions:
    admin_password: ${addons.observability.admin_password ?? "grafana"}

# Ingress
- name: ingress
  path: ingress
  when: ingress.enabled == true && ingress.driver == 'nginx' && vm.driver == 'docker-desktop'
  dependsOn:
  - pki-base
  components:
  - nginx/nodeport
  - nginx/prometheus
  timeout: 10m
  interval: 5m

# Demo database cluster
- name: demo-database
  path: demo
  when: demo == true
  dependsOn:
  - database
  components:
  - database
