kind: Facet
apiVersion: blueprints.windsorcli.dev/v1alpha1
metadata:
  name: incus
  description: Incus compute platform infrastructure

when: provider == 'incus'

terraform:

- name: compute
  path: compute/incus
  inputs:
    network_name: "${vm.driver == 'colima' ? 'incusbr0' : ''}"
    create_network: "${vm.driver != 'colima'}"
    network_cidr: ${network.cidr_block}
    storage_pools:
      local:
        driver: "${vm.driver == 'colima' ? 'dir' : null}"
    instances:
      - name: controlplane
        role: controlplane
        count: ${cluster.controlplanes.count ?? 1}
        ipv4: ${cidrhost(network.cidr_block, 10)}
        image: windsor:talos/v1.12.1/arm64
        type: virtual-machine
        description: Talos control plane node
        storage_pool: "${vm.driver == 'colima' ? 'local' : 'default'}"
        root_disk_size: ${string(cluster.controlplanes.root_disk_size ?? 30) + "GB"}
        limits:
          cpu: ${string(cluster.controlplanes.cpu ?? 2)}
          memory: ${string(cluster.controlplanes.memory ?? 2) + "GB"}
        disks: ${cluster.controlplanes.disks ?? []}
        config:
          user.hostname: ${values(cluster.controlplanes.nodes)[0].hostname ?? "controlplane-1"}
          environment.TALOSSKU: ${string(cluster.controlplanes.cpu ?? 2) + "CPU-" + string(cluster.controlplanes.memory ?? 2) + "GB"}
          raw.qemu: -boot order=c,menu=off
      - name: worker
        role: worker
        count: ${cluster.workers.count ?? 0}
        ipv4: ${cidrhost(network.cidr_block, 20)}
        image: windsor:talos/v1.12.1/arm64
        type: virtual-machine
        description: Talos worker node
        storage_pool: "${vm.driver == 'colima' ? 'local' : 'default'}"
        root_disk_size: ${string(cluster.workers.root_disk_size ?? 50) + "GB"}
        limits:
          cpu: ${string(cluster.workers.cpu ?? 4)}
          memory: ${string(cluster.workers.memory ?? 4) + "GB"}
        disks: ${cluster.workers.disks ?? []}
        config:
          user.hostname: "${cluster.workers.nodes != null ? (values(cluster.workers.nodes)[0].hostname ?? 'worker-1') : 'worker-1'}"
          environment.TALOSSKU: "${string(cluster.workers.cpu ?? 4) + 'CPU-' + string(cluster.workers.memory ?? 4) + 'GB'}"
          raw.qemu: -boot order=c,menu=off

- name: cluster
  path: cluster/talos
  dependsOn:
  - compute
  parallelism: 1
  inputs:
    cluster_endpoint: ${cluster.endpoint ?? ("https://" + split(terraform_output("compute", "controlplanes")[0].endpoint, ":")[0] + ":6443")}
    cluster_name: talos
    controlplanes: ${terraform_output("compute", "controlplanes") ?? values(cluster.controlplanes.nodes)}
    workers: "${terraform_output('compute', 'workers') ?? (cluster.workers.nodes != null ? values(cluster.workers.nodes) : [])}"
    common_config_patches: ${jsonnet("../configs/talos-generic.jsonnet").common_config_patches}
    worker_config_patches: ${jsonnet("../configs/talos-generic.jsonnet").worker_config_patches}
    controlplane_config_patches: ${jsonnet("../configs/talos-generic.jsonnet").controlplane_config_patches}
- name: gitops
  path: gitops/flux
  dependsOn:
  - cluster
  inputs:
    concurrency: ${max(2, min(floor((cluster.controlplanes.cpu ?? 4) / 2), floor((cluster.controlplanes.memory ?? 4) / 2), 10))}
  destroy: false

kustomize:

# CSI
- name: csi
  path: csi
  dependsOn:
    - policy-resources
  components:
  - openebs
  - openebs/dynamic-localpv
  substitutions:
    local_volume_path: "${cluster.controlplanes.schedulable == true ? split(cluster.controlplanes.volumes[0] ?? '/var/local', ':')[len(split(cluster.controlplanes.volumes[0] ?? '/var/local', ':')) - 1] : split(cluster.workers.volumes[0] ?? '/var/local', ':')[len(split(cluster.workers.volumes[0] ?? '/var/local', ':')) - 1]}"
  timeout: 20m
  interval: 5m

# Load Balancer
- name: lb-base
  path: lb/base
  dependsOn:
    - policy-resources
  components:
    - "${network.loadbalancer_driver == 'metallb' ? 'metallb' : ''}"
  timeout: 5m
  interval: 5m

- name: lb-resources
  path: lb/resources
  dependsOn:
    - lb-base
  components:
    - ${network.loadbalancer_driver}
    - "${network.loadbalancer_driver}/${network.loadbalancer_mode}"
  substitutions:
    loadbalancer_ip_range: "${network.loadbalancer_ips.start + '-' + network.loadbalancer_ips.end}"
  timeout: 5m
  interval: 5m
