kind: Facet
apiVersion: blueprints.windsorcli.dev/v1alpha1
metadata:
  name: provider-base
  description: "Base infrastructure components for all providers"

when: provider != 'none'

kustomize:

# Cleanup
- name: cleanup
  path: cleanup
  destroyOnly: true
  components:
  - ingresses
  - loadbalancers
  - pvcs
  timeout: 10m
  interval: 5m

# Policy
- name: policy-base
  path: policy/base
  components:
    - kyverno
  timeout: 30m
  interval: 5m

- name: policy-resources
  path: policy/resources
  dependsOn:
    - policy-base
  components:
    - kyverno/audit-resource-limits-requests
    - kyverno/require-image-digest
  timeout: 5m
  interval: 5m

# PKI
- name: pki-base
  path: pki/base
  dependsOn:
    - policy-resources
    - telemetry-base
  components:
    - cert-manager
    - cert-manager/prometheus
  timeout: 20m
  interval: 5m

# Telemetry
- name: telemetry-base
  path: telemetry/base
  components:
    - prometheus
    - prometheus/flux
    - fluentbit
  timeout: 30m
  interval: 10m
- name: telemetry-resources
  path: telemetry/resources
  dependsOn:
    - telemetry-base
  components:
    - metrics-server
    - prometheus
    - prometheus/flux
    - fluentbit
    - fluentbit/containerd
    - fluentbit/kubernetes
    - fluentbit/parser
    - fluentbit/systemd
    - fluentbit/prometheus
    - "${(telemetry.log_aggregation.driver ?? 'fluentd') == 'fluentd' ? 'fluentbit/fluentd' : ''}"
  timeout: 10m
  interval: 5m

# FluentD aggregator (log aggregation driver, runs in observability namespace for security)
# Independent of observability addon - FluentD is part of base telemetry infrastructure
# Excluded when elasticsearch is used (which uses filebeat instead) or when log aggregation driver is not fluentd
- name: observability
  path: observability
  when: (telemetry.log_aggregation.driver ?? 'fluentd') == 'fluentd' && (addons.observability.logs_driver ?? '') != 'elasticsearch'
  components:
    - fluentd
    - fluentd/filters/otel
    - fluentd/prometheus
    - "${log_level != 'trace' ? 'fluentd/filters/log-level/' + (log_level ?? 'info') : ''}"
  timeout: 15m
  interval: 10m
