kind: Facet
apiVersion: blueprints.windsorcli.dev/v1alpha1
metadata:
  name: azure
  description: "Azure provider basic infrastructure"

when: provider == 'azure'

terraform:
- name: network
  path: network/azure-vnet
  inputs:
    vnet_cidr: ${network.cidr_block}
- name: cluster
  path: cluster/azure-aks
  dependsOn:
    - network
- name: gitops
  path: gitops/flux
  destroy: false
  dependsOn:
    - cluster
  inputs:
    concurrency: 5

kustomize:

# Ingress
- name: ingress
  path: ingress
  when: ingress?.enabled == true && ingress?.driver == 'nginx'
  dependsOn:
    - pki-base
  components:
    - nginx
    - nginx/coredns
    - nginx/web
  timeout: 10m
  interval: 5m

# CSI
- name: csi
  path: csi
  dependsOn:
    - policy-resources
  components:
    - azure-disk
  timeout: 5m
  interval: 5m
  substitutions:
    single_storage_type: ${cluster.storage?.single_storage_type ?? "StandardSSD_LRS"}

# Telemetry - exclude metrics-server as AKS provides it natively
- name: telemetry-resources
  path: telemetry/resources
  strategy: remove
  components:
    - metrics-server
  timeout: 5m
  interval: 5m
