kind: Facet
apiVersion: blueprints.windsorcli.dev/v1alpha1
metadata:
  name: metal
  description: "Metal provider basic infrastructure"

when: provider == 'metal'

terraform:
- name: cluster
  path: cluster/talos
  parallelism: 1
  inputs:
    cluster_endpoint: ${cluster.endpoint ?? ("https://" + split(values(cluster.controlplanes.nodes)[0].endpoint, ":")[0] + ":6443")}
    cluster_name: talos
    controlplanes: ${values(cluster.controlplanes.nodes)}
    workers: "${(cluster.workers.count ?? 0) > 0 ? values(cluster.workers.nodes) : []}"
    common_config_patches: ${jsonnet("../configs/talos-generic.jsonnet").common_config_patches}
    worker_config_patches: ${jsonnet("../configs/talos-generic.jsonnet").worker_config_patches}
    controlplane_config_patches: ${jsonnet("../configs/talos-generic.jsonnet").controlplane_config_patches}
- name: gitops
  path: gitops/flux
  dependsOn:
    - cluster
  inputs:
    concurrency: ${max(2, min(floor((cluster.controlplanes.cpu ?? 4) / 2), floor((cluster.controlplanes.memory ?? 4) / 2), 10))}
  destroy: false

kustomize:

# CSI
- name: csi
  path: csi
  dependsOn:
    - policy-resources
  components:
    - openebs
    - openebs/dynamic-localpv
  substitutions:
    local_volume_path: ${cluster.workers.volumes[0]}
  timeout: 20m
  interval: 5m

# Load Balancer
- name: lb-base
  path: lb/base
  when: vm.driver != 'docker-desktop'
  dependsOn:
    - policy-resources
  components:
    - "${network.loadbalancer_driver == 'metallb' ? 'metallb' : ''}"
  timeout: 5m
  interval: 5m

- name: lb-resources
  path: lb/resources
  when: vm.driver != 'docker-desktop'
  dependsOn:
    - lb-base
  components:
    - ${network.loadbalancer_driver}
    - "${network.loadbalancer_driver}/${network.loadbalancer_mode}"
  substitutions:
    loadbalancer_ip_range: ${network.loadbalancer_ips.start + '-' + network.loadbalancer_ips.end}
  timeout: 5m
  interval: 5m

