apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# Application-credential Role and Database. Peer to ../instance-connection
# for the ProviderConfig.

resources:
  - role.yaml
  - database.yaml
