---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coredns
  namespace: system-dns
spec:
  interval: 5m
  timeout: 10m
  dependsOn: []
  chart:
    spec:
      chart: coredns
      # renovate: datasource=helm depName=coredns package=coredns helmRepo=https://coredns.github.io/helm
      version: 1.42.1
      sourceRef: 
        kind: HelmRepository
        name: coredns
        namespace: system-gitops
  values:
    isClusterService: false
    extraVolumes: []
    extraVolumeMounts: []
    servers:
      - zones:
          - zone: .
        port: 53
        plugins:
          - name: errors
          - name: health
            configBlock: |-
              lameduck 5s
          - name: forward
            parameters: . 1.1.1.1 8.8.8.8
          - name: ready
          - name: prometheus
            parameters: 0.0.0.0:9153
          - name: cache
            parameters: 30
          - name: loop
          - name: reload
          - name: loadbalance
