---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coredns
  namespace: system-dns
spec:
  interval: 5m
  timeout: 10m
  dependsOn: []
  chart:
    spec:
      chart: coredns
      # renovate: datasource=helm depName=coredns package=coredns helmRepo=https://coredns.github.io/helm
      version: 1.45.0
      sourceRef: 
        kind: HelmRepository
        name: coredns
        namespace: system-gitops
  values:
    image:
      # renovate: datasource=docker depName=coredns/coredns package=coredns/coredns
      tag: 1.14.0@sha256:4fbdd8fb53c5d1748aeb98f0799798fb073bb11128c13e8415aa254ad1ae0203
    isClusterService: false
    extraVolumes: []
    extraVolumeMounts: []
    servers:
      - zones:
          - zone: .
        port: 53
        plugins:
          - name: errors
          - name: health
            configBlock: |-
              lameduck 5s
          - name: forward
            parameters: . 1.1.1.1 8.8.8.8
          - name: ready
          - name: prometheus
            parameters: 0.0.0.0:9153
          - name: cache
            parameters: 30
          - name: loop
          - name: reload
          - name: loadbalance
