apiVersion: v1
kind: ServiceAccount
metadata:
  name: kyverno-webhook-probe
  namespace: system-policy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kyverno-webhook-probe
  namespace: system-policy
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kyverno-webhook-probe
  namespace: system-policy
subjects:
- kind: ServiceAccount
  name: kyverno-webhook-probe
  namespace: system-policy
roleRef:
  kind: Role
  name: kyverno-webhook-probe
  apiGroup: rbac.authorization.k8s.io
