---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx-controller
  namespace: system-ingress
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: ingress-nginx
      # renovate: datasource=helm depName=ingress-nginx package=ingress-nginx helmRepo=https://kubernetes.github.io/ingress-nginx
      version: 4.13.1
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: system-ingress
  values:
    controller:
      service:
        enableHttp: false
        enableTls: false
      ingressClassResource:
        default: true
