---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: system-ingress
spec:
  interval: 10m
  timeout: 3m
  url: https://kubernetes.github.io/ingress-nginx
