---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx-controller
  namespace: system-ingress
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: ingress-nginx
      # renovate: datasource=helm depName=ingress-nginx package=ingress-nginx helmRepo=https://kubernetes.github.io/ingress-nginx
      version: 4.15.1
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: system-ingress
  values:
    controller:
      image:
        # renovate: datasource=docker depName=registry.k8s.io/ingress-nginx/controller package=registry.k8s.io/ingress-nginx/controller
        tag: v1.15.1@sha256:594ceea76b01c592858f803f9ff4d2cb40542cae2060410b2c95f75907d659e1
        digest: ""
        digestChroot: ""
      service:
        enableHttp: false
        enableTls: false
      ingressClassResource:
        default: true
