apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: system-gitops
spec:
  interval: 10m
  timeout: 5m
  type: ${helm_repo_type:=default}
  url: ${helm_registry:=https://prometheus-community.github.io/helm-charts}
  insecure: ${helm_repo_insecure:=false}
