apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: system-telemetry
spec:
  interval: 5m
  timeout: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      # renovate: datasource=helm depName=kube-prometheus-stack package=kube-prometheus-stack helmRepo=https://prometheus-community.github.io/helm-charts
      version: 84.4.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  values:
    grafana:
      enabled: false
    kubeStateMetrics:
      enabled: true
    kube-state-metrics:
      image:
        # renovate: datasource=docker depName=registry.k8s.io/kube-state-metrics/kube-state-metrics package=registry.k8s.io/kube-state-metrics/kube-state-metrics
        tag: v2.18.0@sha256:1545919b72e3ae035454fc054131e8d0f14b42ef6fc5b2ad5c751cafa6b2130e
    prometheusOperator:
      image:
        # renovate: datasource=docker depName=quay.io/prometheus-operator/prometheus-operator package=quay.io/prometheus-operator/prometheus-operator
        tag: v0.90.1@sha256:52a6a92d915ea2fa94314748d99db7a94922e3fe63274f6182fc033b9126b573
      prometheusConfigReloader:
        image:
          # renovate: datasource=docker depName=quay.io/prometheus-operator/prometheus-config-reloader package=quay.io/prometheus-operator/prometheus-config-reloader
          tag: v0.90.1@sha256:693faa0b87243cddca2cffb13586e4e2778b0cdf319cb2e601ba7af3fd19ef7d
      admissionWebhooks:
        patch:
          image:
            # renovate: datasource=docker depName=ghcr.io/jkroepke/kube-webhook-certgen package=ghcr.io/jkroepke/kube-webhook-certgen
            tag: 1.8.2@sha256:e133b64c08377a107298ac3352504bd3cd21f13282bc2aac099a88a7888b3f54
    prometheus:
      prometheusSpec:
        # renovate: datasource=github-releases depName=prometheus/prometheus package=prometheus/prometheus
        version: v3.11.3
        image:
          # renovate: datasource=docker depName=quay.io/prometheus/prometheus package=quay.io/prometheus/prometheus
          tag: v3.11.3@sha256:c0b857aead0d5793aa566adb8f49a9983d6f6031652098759d521a330cfa050f
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        serviceMonitorNamespaceSelector: { }
        serviceMonitorSelector: { }
        podMonitorNamespaceSelector: { }
        podMonitorSelector: { }
    nodeExporter:
      enabled: true
      replicas: 1
    prometheus-node-exporter:
      # renovate: datasource=github-releases depName=prometheus/node_exporter package=prometheus/node_exporter
      version: v1.11.1
      image:
        # renovate: datasource=docker depName=quay.io/prometheus/node-exporter package=quay.io/prometheus/node-exporter
        tag: v1.11.1@sha256:0f422f62c15f154af8d8572b23d623aebfb10cec73a5c654d18f911f3f9df241
        digest: ""
