apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: system-lb
spec:
  interval: 5m
  timeout: 5m
  chart:
    spec:
      chart: metallb
      # renovate: datasource=helm depName=metallb package=metallb helmRepo=https://metallb.github.io/metallb
      version: 0.14.9
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: system-gitops
