apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: system-lb
spec:
  interval: 5m
  timeout: 5m
  chart:
    spec:
      chart: metallb
      # renovate: datasource=helm depName=metallb package=metallb helmRepo=https://metallb.github.io/metallb
      version: 0.15.2
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: system-gitops
  values:
    controller:
      image:
        # renovate: datasource=docker depName=quay.io/metallb/controller package=quay.io/metallb/controller
        tag: v0.15.2@sha256:417cdb6d6f9f2c410cceb84047d3a4da3bfb78b5ddfa30f4cf35ea5c667e8c2e
    speaker:
      image:
        # renovate: datasource=docker depName=quay.io/metallb/speaker package=quay.io/metallb/speaker
        tag: v0.15.2@sha256:260c9406f957c0830d4e6cd2e9ac8c05e51ac959dd2462c4c2269ac43076665a
      frr:
        image:
          # renovate: datasource=docker depName=quay.io/frrouting/frr package=quay.io/frrouting/frr
          tag: 9.1.3@sha256:e78319c08c8cff0667bea724b9fcd50db5ecac70b03ac28b2f518cf6342f7fab
