---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluent-operator
  namespace: system-telemetry
spec:
  dependsOn:
    - name: kube-prometheus-stack
      namespace: system-telemetry
  values:
    fluentbit:
      serviceMonitor:
        enable: true
