---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trust-manager
  namespace: system-pki-trust
spec:
  interval: 5m
  timeout: 10m
  dependsOn:
    - name: cert-manager
      namespace: system-pki
  chart:
    spec:
      chart: trust-manager
      # renovate: datasource=helm depName=trust-manager package=trust-manager helmRepo=https://charts.jetstack.io
      version: 0.20.3
      sourceRef: 
        kind: HelmRepository
        name: jetstack
        namespace: system-gitops
  values:
    image:
      # renovate: datasource=docker depName=quay.io/jetstack/trust-manager package=quay.io/jetstack/trust-manager
      tag: v0.20.3@sha256:7047bcd17f31fd381d6a6866ed991d1a21b7a4d8832cb4b11b2cdb342ffc02dd
    defaultPackageImage:
      # renovate: datasource=docker depName=quay.io/jetstack/trust-pkg-debian-bookworm package=quay.io/jetstack/trust-pkg-debian-bookworm
      tag: 20230311-deb12u1.2@sha256:f9a6f14926da740c2831a738393f061b22594ec5d47ff55f68b1f59cfb9bf543
    app:
      trust:
        namespace: system-pki-trust
