---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trust-manager
  namespace: system-pki-trust
spec:
  interval: 5m
  timeout: 10m
  dependsOn:
    - name: cert-manager
      namespace: system-pki
  chart:
    spec:
      chart: trust-manager
      # renovate: datasource=helm depName=trust-manager package=trust-manager helmRepo=https://charts.jetstack.io
      version: 0.12.0
      sourceRef: 
        kind: HelmRepository
        name: jetstack
        namespace: system-gitops
  values:
    app:
      trust:
        namespace: system-pki-trust
