---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trust-manager
  namespace: system-pki-trust
spec:
  interval: 5m
  timeout: 10m
  dependsOn:
    - name: cert-manager
      namespace: system-pki
  chart:
    spec:
      chart: trust-manager
      # renovate: datasource=helm depName=trust-manager package=trust-manager helmRepo=https://charts.jetstack.io
      version: 0.22.0
      sourceRef: 
        kind: HelmRepository
        name: jetstack
        namespace: system-gitops
  values:
    image:
      # renovate: datasource=docker depName=quay.io/jetstack/trust-manager package=quay.io/jetstack/trust-manager
      tag: v0.22.1@sha256:23e2ab0711d77c3d25a7297d480883e8d037659db88dcdc0dab788a08a1b2097
    defaultPackageImage:
      # renovate: datasource=docker depName=quay.io/jetstack/trust-pkg-debian-bookworm package=quay.io/jetstack/trust-pkg-debian-bookworm
      tag: 20230311-deb12u1.2@sha256:f9a6f14926da740c2831a738393f061b22594ec5d47ff55f68b1f59cfb9bf543
    app:
      trust:
        namespace: system-pki-trust
