apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  labels:
    fluentbit.fluent.io/component: logging
    fluentbit.fluent.io/enabled: "true"
  name: suppress
spec:
  # Run after service-name filter (ordinal 100) since we match on service_name
  ordinal: 105
  match: kube.*
  filters:
  - lua:
      call: suppress
      script:
        key: suppress.lua
        name: fluent-bit-suppress-config
      timeAsTable: true
