---
apiVersion: database.windsorcli.dev/v1alpha1
kind: DatabaseCredentials
metadata:
  name: demo-app
  namespace: demo-database
spec:
  driver: flexibleserver
  instanceName: demo-db
  databaseName: ${demo_database_name}
