---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx-controller
  namespace: system-ingress
spec:
  values:
    controller:
      service:
        enableUDP: true
        nodePorts:
          udp:
            "53": 30053
          tcp:
            "53": 30053
    udp:
      "53": "system-dns/coredns:53"
    tcp:
      "53": "system-dns/coredns:53"
