apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quickwit-indexes
  namespace: system-observability
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
