---
# The shared external-dns ServiceAccount, bound to the external-dns identity.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: system-dns
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: ${external_dns_client_id}
    azure.workload.identity/tenant-id: ${external_dns_tenant_id}
