apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-vip
  namespace: system-lb
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: kube-vip
      # renovate: datasource=helm depName=kube-vip package=kube-vip helmRepo=https://kube-vip.github.io/helm-charts
      version: 0.9.9
      sourceRef:
        kind: HelmRepository
        name: kube-vip
  values:
    image:
      repository: ghcr.io/kube-vip/kube-vip
      # renovate: datasource=docker depName=ghcr.io/kube-vip/kube-vip package=ghcr.io/kube-vip/kube-vip
      tag: v1.2.0@sha256:fe8c7b6641ba7633a12b337821e9e83a6456e8edc3434f97577058edd4eecaf6
    env:
      svc_enable: "true"
      svc_election: "true"
