---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elasticsearch
  namespace: system-observability
spec:
  secretName: elasticsearch-master-certs
  issuerRef:
    name: private
    kind: ClusterIssuer
  commonName: elasticsearch
  dnsNames:
    - "elasticsearch-master"
    - "elasticsearch-master.system-observability"
    - "elasticsearch-master.system-observability.svc"
    - "elasticsearch-master.system-observability.svc.${CLUSTER_DOMAIN:-cluster.local}"
    - "*.elasticsearch-master.system-observability.svc.${CLUSTER_DOMAIN:-cluster.local}"
    - "elasticsearch-master-headless"
    - "elasticsearch-master-headless.system-observability"
    - "elasticsearch-master-headless.system-observability.svc"
    - "elasticsearch-master-headless.system-observability.svc.${CLUSTER_DOMAIN:-cluster.local}"
    - "*.elasticsearch-master-headless.system-observability.svc.${CLUSTER_DOMAIN:-cluster.local}"
  usages:
    - server auth
    - client auth
