apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: elastic-elasticsearch
  namespace: system-observability
spec:
  interval: 10m
  type: ${helm_repo_type:=default}
  url: ${helm_registry:=https://helm.elastic.co}
  insecure: ${helm_repo_insecure:=false}
