apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: system-observability
spec:
  interval: 5m
  timeout: 15m
  dependsOn: []
  chart:
    spec:
      chart: grafana
      # renovate: datasource=helm depName=grafana package=grafana helmRepo=https://grafana.github.io/helm-charts
      version: 10.5.15
      sourceRef:
        kind: HelmRepository
        name: grafana
  values:
    grafana.ini:
      date_formats:
        full_date: ${date_full:-YYYY-MM-DD HH:mm:ss}
        interval_second: ${date_interval_second:-HH:mm:ss}
        interval_minute: ${date_interval_minute:-HH:mm}
        interval_hour: ${date_interval_hour:-MM/DD HH:mm}
        interval_day: ${date_interval_day:-MM/DD}
        interval_month: YYYY-MM
        interval_year: YYYY
      default:
        timezone: ${timezone:-utc}
    image:
      # renovate: datasource=docker depName=grafana/grafana package=grafana/grafana
      tag: 13.1.2@sha256:d177053ab62253815f130d81504f77063baf5fd4ca93299d6048453bd31e047a
    initChownData:
      image:
        # renovate: datasource=docker depName=library/busybox package=library/busybox
        tag: 1.38.0@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616
    downloadDashboardsImage:
      # renovate: datasource=docker depName=curlimages/curl package=curlimages/curl
      tag: 8.21.0@sha256:7c12af72ceb38b7432ab85e1a265cff6ae58e06f95539d539b654f2cfa64bb13
    sidecar:
      image:
        # renovate: datasource=docker depName=kiwigrid/k8s-sidecar package=kiwigrid/k8s-sidecar
        tag: 2.10.0@sha256:21b9fe7bb29d65caf2445ccbf96ff6eda5e589a92bd8f5188f957fe75b551d72
      dashboards:
        enabled: true
        label: grafana_dashboard
        labelValue: "1"
        folder: /var/lib/grafana/dashboards/sidecar
        folderAnnotation: grafana_folder
        provider:
          foldersFromFilesStructure: true
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers: []
    dashboards: {}
    plugins: []
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources: []
