kind: Blueprint
apiVersion: blueprints.windsorcli.dev/v1alpha1
metadata:
  name: metal-example
  description: This blueprint outlines resources in the metal-example context
repository:
  url: ""
  ref:
    branch: main
  secretName: flux-system
sources:
- name: core
  url: github.com/windsorcli/core
  ref:
    branch: main
terraform:
- source: core
  path: cluster/talos
- source: core
  path: gitops/flux
  destroy: false
kustomize:
- name: telemetry-base
  path: telemetry/base
  source: core
  components:
  - prometheus
  - prometheus/flux
- name: telemetry-resources
  path: telemetry/resources
  source: core
  dependsOn:
  - telemetry-base
  components:
  - metrics-server
  - prometheus
  - prometheus/flux
- name: policy-base
  path: policy/base
  source: core
  components:
  - kyverno
- name: policy-resources
  path: policy/resources
  source: core
  dependsOn:
  - policy-base
- name: csi
  path: csi
  source: core
  dependsOn:
  - policy-resources
  force: true
  components:
  - openebs
  - openebs/mayastor
- name: lb-base
  path: lb/base
  source: core
  dependsOn:
  - policy-resources
  force: true
  components:
  - metallb
- name: lb-resources
  path: lb/resources
  source: core
  dependsOn:
  - lb-base
  force: true
  components:
  - metallb/layer2
- name: ingress
  path: ingress
  source: core
  dependsOn:
  - pki-resources
  force: true
  components:
  - nginx
  - nginx/loadbalancer
  - nginx/coredns
  - nginx/flux-webhook
  - nginx/web
- name: pki-base
  path: pki/base
  source: core
  dependsOn:
  - policy-resources
  force: true
  components:
  - cert-manager
  - trust-manager
- name: pki-resources
  path: pki/resources
  source: core
  dependsOn:
  - pki-base
  force: true
  components:
  - private-issuer/ca
  - public-issuer/selfsigned
- name: dns
  path: dns
  source: core
  dependsOn:
  - pki-base
  force: true
  components:
  - coredns
  - coredns/etcd
  - external-dns
  - external-dns/coredns
  - external-dns/ingress
- name: gitops
  path: gitops/flux
  source: core
  dependsOn:
  - ingress
  force: true
  components:
  - webhook
- name: observability
  path: observability
  source: core
  dependsOn:
  - ingress
  components:
  - grafana
  - grafana/ingress
  - grafana/prometheus
  - grafana/node
  - grafana/kubernetes
  - grafana/flux
