apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: single
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: disk.csi.azure.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  skuName: Premium_LRS
  cachingMode: ReadWrite
  fsType: ext4
reclaimPolicy: Delete
