---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: quickwit
  namespace: system-observability
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: quickwit
      # renovate: datasource=helm depName=quickwit package=quickwit helmRepo=https://helm.quickwit.io
      version: 0.7.17
      sourceRef: 
        kind: HelmRepository
        name: quickwit
        namespace: system-gitops
  values:
    searcher:
      replicaCount: 1
