---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fluent-operator
  namespace: system-gitops
spec:
  interval: 5m0s
  url: https://github.com/fluent/fluent-operator
  ref:
    commit: fadeede85a4a77ff43aba702dee7bf669bb43f20
