---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluent-operator
  namespace: system-telemetry
spec:
  interval: 5m
  timeout: 5m
  chart:
    spec:
      chart: charts/fluent-operator
      # renovate: datasource=helm depName=fluent-operator package=fluent-operator helmRepo=https://fluent.github.io/helm-charts
      version: 3.5.0
      sourceRef:
        kind: GitRepository
        name: fluent-operator
        namespace: system-gitops
  values:
    containerRuntime: containerd
    Kubernetes: false
    fluentd:
      enable: false
      crdsEnable: true
    fluentbit:
      enable: false
      crdsEnable: true
