---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluent-operator
  namespace: system-telemetry
spec:
  interval: 5m
  timeout: 20m
  chart:
    spec:
      chart: fluent-operator
      # renovate: datasource=helm depName=fluent-operator package=fluent-operator helmRepo=https://fluent.github.io/helm-charts
      version: 4.0.0
      sourceRef:
        kind: HelmRepository
        name: fluent
  values:
    operator:
      image:
        # renovate: datasource=docker depName=ghcr.io/fluent/fluent-operator/fluent-operator package=ghcr.io/fluent/fluent-operator/fluent-operator
        tag: v3.7.0@sha256:680714f4eccfe174305bfd187d4f7ba5c6aa24b8ce952807343c39a92d56bbed
      initcontainer:
        image:
          # renovate: datasource=docker depName=docker.io/library/docker package=docker.io/library/docker
          tag: 20.10@sha256:2967f0819c84dd589ed0a023b9d25dcfe7a3c123d5bf784ffbb77edf55335f0c
    containerRuntime: containerd
    Kubernetes: false
    fluentd:
      image:
        # renovate: datasource=docker depName=ghcr.io/fluent/fluent-operator/fluentd package=ghcr.io/fluent/fluent-operator/fluentd
        tag: v1.19.2@sha256:fef9f961b919a56c7f11b0d6edcd55693150cc72d9728aac4b7a95937336774f
      enable: false
      crdsEnable: true
    fluentbit:
      image:
        # renovate: datasource=docker depName=ghcr.io/fluent/fluent-operator/fluent-bit package=ghcr.io/fluent/fluent-operator/fluent-bit
        tag: v5.0.4@sha256:d43770be9c0ae7ddb4e9800846dffbf8522b30e1bd8e7eac83c4d2a342e30011
      enable: false
      crdsEnable: true
