---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: 1password
  namespace: system-gitops
spec:
  interval: 10m
  timeout: 5m
  url: https://1password.github.io/connect-helm-charts/
