---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: system-secrets
spec:
  interval: 10m
  timeout: 3m
  url: https://charts.external-secrets.io
