---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: system-secrets
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: external-secrets
      # renovate: datasource=helm depName=external-secrets package=external-secrets helmRepo=https://charts.external-secrets.io
      version: 2.8.0
      sourceRef:
        kind: HelmRepository
        name: external-secrets
  values:
    installCRDs: false
    image:
      # renovate: datasource=docker depName=ghcr.io/external-secrets/external-secrets package=ghcr.io/external-secrets/external-secrets
      tag: v2.8.0@sha256:24c0dd3699e0988520afd2218612758cd97d1f702757b5b4fcf89adaa33ef679
    webhook:
      image:
        # renovate: datasource=docker depName=ghcr.io/external-secrets/external-secrets package=ghcr.io/external-secrets/external-secrets
        tag: v2.8.0@sha256:24c0dd3699e0988520afd2218612758cd97d1f702757b5b4fcf89adaa33ef679
    certController:
      image:
        # renovate: datasource=docker depName=ghcr.io/external-secrets/external-secrets package=ghcr.io/external-secrets/external-secrets
        tag: v2.8.0@sha256:24c0dd3699e0988520afd2218612758cd97d1f702757b5b4fcf89adaa33ef679
