apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: set-ingress-localhost-dns-target
spec:
  validationFailureAction: audit
  background: false
  rules:
    - name: add-external-dns-annotation
      match:
        resources:
          kinds:
            - Ingress
      mutate:
        patchStrategicMerge:
          metadata:
            annotations:
              external-dns.alpha.kubernetes.io/target: "127.0.0.1"
