---
apiVersion: database.windsorcli.dev/v1alpha1
kind: DatabaseCredentials
metadata:
  name: demo-db-monitor
  namespace: system-database
spec:
  target:
    apiVersion: sql.gcp.upbound.io/v1beta2
    kind: DatabaseInstance
    name: ${database_instance_name}
  roleName: monitor
  secretName: ${demo_monitor_secret_name}
  grants:
    - memberOf: pg_monitor
