apiVersion: fluentd.fluent.io/v1alpha1
kind: ClusterFilter
metadata:
  name: otel
  labels:
    filter.fluentd.fluent.io/enabled: "true"
spec:
  filters:
    - recordTransformer:
        enableRuby: true
        renewRecord: false
        removeKeys: "logtag,time,log,kubernetes,attr_http_request_method,attr_http_response_status_code,attr_url_path,attr_client_address,attr_http_request_duration,attr_server_address,attr_network_protocol_name,attr_network_peer_address"
        records:
          - key: timestamp_nanos
            value: |
              $${Time.parse(record["time"]).to_i * 1_000_000_000 + Time.parse(record["time"]).nsec}
          - key: service_name
            value: |
              $${record["service_name"] || record.dig("kubernetes", "container_name") || ""}
          - key: severity_text
            value: |
              $${record["severity_text"] || ""}
          - key: body
            value: |
              $${{"message" => (record["body"] || record["log"])}}
          - key: attributes
            value: |
              $${attrs = {}; record.each { |k, v| attrs[k.sub("attr_", "").gsub("_", ".")] = v if k.start_with?("attr_") && v }; attrs.empty? ? nil : attrs}
          - key: resource_attributes
            value: |
              $${{"k8s.namespace.name" => record.dig("kubernetes", "namespace_name"), "k8s.pod.name" => record.dig("kubernetes", "pod_name"), "k8s.container.name" => record.dig("kubernetes", "container_name"), "container.image.name" => record.dig("kubernetes", "container_image"), "container.image.id" => record.dig("kubernetes", "docker_id")}}
