apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: system-cni
spec:
  values:
    hubble:
      enabled: true
      metrics:
        enabled:
          - dns
          - drop
          - port-distribution
          - tcp
          - flow
          - icmp
          - http
        serviceMonitor:
          enabled: true
      relay:
        enabled: true
      ui:
        enabled: false
