---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openbao
  namespace: system-secrets-store
spec:
  dependsOn:
    - name: kube-prometheus-stack
      namespace: system-telemetry
  values:
    serverTelemetry:
      serviceMonitor:
        enabled: true
        selectors:
          release: kube-prometheus-stack
        tlsConfig:
          insecureSkipVerify: true
