---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnativepg
  namespace: system-database
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: cloudnative-pg
      # renovate: datasource=helm depName=cloudnative-pg package=cloudnative-pg helmRepo=https://cloudnative-pg.github.io/charts
      version: "0.25.0"
      sourceRef:
        kind: HelmRepository
        name: cloudnativepg
        namespace: system-gitops
  values:
    config:
      clusterWide: true
    image:
      # renovate: datasource=docker depName=ghcr.io/cloudnative-pg/cloudnative-pg package=ghcr.io/cloudnative-pg/cloudnative-pg
      tag: 1.28.0@sha256:34198e85b6e6dd81471cb1c3ee222ca5231b685220e7ae38a634d35ed4826a40
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        memory: 256Mi
    containerSecurityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
    webhook:
      mutating:
        failurePolicy: Fail
      validating:
        failurePolicy: Fail
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 0
