---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cloudnativepg
  namespace: system-gitops
spec:
  interval: 10m
  timeout: 3m
  url: https://cloudnative-pg.github.io/charts
