apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  labels:
    fluentbit.fluent.io/component: logging
    fluentbit.fluent.io/enabled: "true"
  name: service-name
spec:
  # Runs last - after all parsing complete
  ordinal: 100
  match: kube.*
  filters:
  - lua:
      call: extract_service_name
      script:
        key: service-name.lua
        name: fluent-bit-service-name-config
      timeAsTable: true
