apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: system-policy
spec:
  interval: 5m
  timeout: 5m
  chart:
    spec:
      chart: kyverno
      # renovate: datasource=helm depName=kyverno package=kyverno helmRepo=https://kyverno.github.io/kyverno/
      version: 3.2.7
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: system-gitops
