---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kyverno
  namespace: system-gitops
spec:
  interval: 10m
  timeout: 3m
  url: https://kyverno.github.io/kyverno
