apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: system-policy
spec:
  interval: 5m
  timeout: 30m
  chart:
    spec:
      chart: kyverno
      # renovate: datasource=helm depName=kyverno package=kyverno helmRepo=https://kyverno.github.io/kyverno/
      version: 3.6.2
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: system-gitops
  values:
    crds:
      migration:
        image:
          # renovate: datasource=docker depName=reg.kyverno.io/kyverno/kyverno-cli package=reg.kyverno.io/kyverno/kyverno-cli
          tag: v1.16.2@sha256:f1a4dd586f118ca24d1fb768b8791a506231748d41cb490dfff04b66b2738079
    # Disable ANSI color codes in logs
    admissionController:
      initContainer:
        image:
          # renovate: datasource=docker depName=reg.kyverno.io/kyverno/kyvernopre package=reg.kyverno.io/kyverno/kyvernopre
          tag: v1.16.2@sha256:ba3a31b25a9e1c6f993d7555158396d87790445ddc785426c249e8320b94b02a
      container:
        image:
          # renovate: datasource=docker depName=reg.kyverno.io/kyverno/kyverno package=reg.kyverno.io/kyverno/kyverno
          tag: v1.16.2@sha256:b0c123d62a1b8e21da707450ef44c4616832434f919d1cd19cfdbe2836277699
        extraEnvVars:
        - name: NO_COLOR
          value: "1"
    backgroundController:
      container:
        image:
          # renovate: datasource=docker depName=reg.kyverno.io/kyverno/background-controller package=reg.kyverno.io/kyverno/background-controller
          tag: v1.17.1@sha256:6d694a404b54368f5ad429f9341e2a9e4e17b8d83bd2ec74643cdaed845d6ea8
        extraEnvVars:
        - name: NO_COLOR
          value: "1"
    cleanupController:
      container:
        image:
          # renovate: datasource=docker depName=reg.kyverno.io/kyverno/cleanup-controller package=reg.kyverno.io/kyverno/cleanup-controller
          tag: v1.17.1@sha256:8789cbf5a89cbc97240de9d07be44a504d76e937fa75a43b27cb891b3d2b01c6
        extraEnvVars:
        - name: NO_COLOR
          value: "1"
    reportsController:
      container:
        image:
          # renovate: datasource=docker depName=reg.kyverno.io/kyverno/reports-controller package=reg.kyverno.io/kyverno/reports-controller
          tag: v1.16.2@sha256:88d0dfc245a689e9bf3e258159b539f3a1b1a5a89f82b6a07c12762527bb7793
        extraEnvVars:
        - name: NO_COLOR
          value: "1"
