---
apiVersion: database.windsorcli.dev/v1alpha1
kind: DatabaseCredentials
metadata:
  name: demo-db-monitor
  namespace: system-database
spec:
  driver: ${demo_db_driver}
  instanceName: demo-db
  roleName: demo-db-monitor
  grants:
    - memberOf: pg_monitor
