---
# Internal load balancer annotation, applied to the internal gateway only.
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: ${gateway_name}
  namespace: system-gateway
spec:
  provider:
    kubernetes:
      envoyService:
        patch:
          type: StrategicMerge
          value:
            metadata:
              annotations:
                service.beta.kubernetes.io/azure-load-balancer-internal: "true"
