apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - provider-config.yaml
  - tag-policy.yaml
  - secret-reader-service-account.yaml
  - kyverno-background-controller-rbac.yaml
  - monitoring-rbac-policy.yaml
  - monitoring-cronjob-policy.yaml
