---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: 1password
  namespace: system-secrets
spec:
  interval: 5m
  timeout: 5m
  chart:
    spec:
      chart: connect
      # renovate: datasource=helm depName=connect package=connect helmRepo=https://1Password.github.io/connect-helm-charts
      version: 1.17.0
      sourceRef:
        kind: HelmRepository
        name: 1password
        namespace: system-gitops
  values:
    connect:
      credentials:
        file: 1password-credentials.json
