---
apiVersion: database.windsorcli.dev/v1alpha1
kind: DatabaseCredentials
metadata:
  name: demo-db-monitor
  namespace: system-database
spec:
  driver: flexibleserver
  instanceName: demo-db-${context_id}
  roleName: demo-db-monitor
  grants:
    - memberOf: pg_monitor
