---
apiVersion: database.windsorcli.dev/v1alpha1
kind: DatabaseCredentials
metadata:
  name: demo-db-monitor
  namespace: system-database
spec:
  target:
    apiVersion: dbforpostgresql.azure.upbound.io/v1beta1
    kind: FlexibleServer
    name: ${database_instance_name}
  roleName: monitor
  secretName: ${demo_monitor_secret_name}
  grants:
    - memberOf: pg_monitor
