---
apiVersion: database.windsorcli.dev/v1alpha1
kind: DatabaseCredentials
metadata:
  name: demo-db-monitor
  namespace: system-database
spec:
  target:
    apiVersion: dbforpostgresql.azure.upbound.io/v1beta1
    kind: FlexibleServer
    name: demo-db-${context_id}
  roleName: demo-db-monitor
  grants:
    - memberOf: pg_monitor
