---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: function-python
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          priorityClassName: windsorcli-platform-critical
          containers:
            - name: package-runtime
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  memory: 128Mi
