---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: system-gitops
spec:
  interval: 10m
  timeout: 3m
  type: ${helm_repo_type:=default}
  url: ${helm_registry:=https://charts.jetstack.io}
  insecure: ${helm_repo_insecure:=false}
