---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: system-pki
spec:
  interval: 5m
  timeout: 20m
  chart:
    spec:
      chart: cert-manager
      # renovate: datasource=helm depName=cert-manager package=cert-manager helmRepo=https://charts.jetstack.io
      version: 1.20.1
      sourceRef: 
        kind: HelmRepository
        name: jetstack
        namespace: system-gitops
  values:
    image:
      # renovate: datasource=docker depName=quay.io/jetstack/cert-manager-controller package=quay.io/jetstack/cert-manager-controller
      tag: v1.20.1@sha256:9f9556b4b131554694c67c8229d231b1f7d69b882b5f061a56bafa465f3b22fc
    webhook:
      image:
        # renovate: datasource=docker depName=quay.io/jetstack/cert-manager-webhook package=quay.io/jetstack/cert-manager-webhook
        tag: v1.20.1@sha256:b876bcaf46ace2a5e860e8371539a6e1c8ccca54b1988a97c8a7483b3815d985
    cainjector:
      image:
        # renovate: datasource=docker depName=quay.io/jetstack/cert-manager-cainjector package=quay.io/jetstack/cert-manager-cainjector
        tag: v1.20.1@sha256:a3ff773a577d8ff6ad1fe9ab4ea0b74873e0341e0aac5d9411f3fc235f51bdf8
    startupapicheck:
      image:
        # renovate: datasource=docker depName=quay.io/jetstack/cert-manager-startupapicheck package=quay.io/jetstack/cert-manager-startupapicheck
        tag: v1.20.1@sha256:70859153f82a241c3a40ac581fb5a25f73db16851adc801f0c8a9c9b220ae4ee
    crds:
      enabled: true
