---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volume-cleanup-role
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims", "persistentvolumes"]
  verbs: ["get", "list", "delete", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: volume-cleanup-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: volume-cleanup-role
subjects:
- kind: ServiceAccount
  name: volume-cleanup
  namespace: system-cleanup
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: volume-cleanup
  namespace: system-cleanup
