---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: system-dns
spec:
  interval: 5m
  timeout: 10m
  dependsOn: []
  chart:
    spec:
      chart: external-dns
      # renovate: datasource=helm depName=external-dns package=external-dns helmRepo=https://kubernetes-sigs.github.io/external-dns/
      version: 1.19.0
      sourceRef: 
        kind: HelmRepository
        name: external-dns
        namespace: system-gitops
  values:
    env: []
    extraVolumes: []
    extraVolumeMounts: []
    sources: []
    domainFilters:
      - "${external_domain:-test}"
