---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-dns
  namespace: system-gitops
spec:
  interval: 10m
  timeout: 3m
  url: https://kubernetes-sigs.github.io/external-dns/
