---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: system-dns
spec:
  interval: 5m
  timeout: 10m
  dependsOn: []
  chart:
    spec:
      chart: external-dns
      # renovate: datasource=helm depName=external-dns package=external-dns helmRepo=https://kubernetes-sigs.github.io/external-dns/
      version: 2.20.4
      sourceRef: 
        kind: HelmRepository
        name: external-dns
        namespace: system-gitops
  values:
    image:
      # renovate: datasource=docker depName=registry.k8s.io/external-dns/external-dns package=registry.k8s.io/external-dns/external-dns
      tag: v0.20.0@sha256:ddc7f4212ed09a21024deb1f470a05240837712e74e4b9f6d1f2632ff10672e7
    env: []
    extraVolumes: []
    extraVolumeMounts: []
    sources: []
    domainFilters:
      - "${DOMAIN:-test}"
