apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio-config
  namespace: system-object-store
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: minio-config
  namespace: system-object-store
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: minio-config
  namespace: system-object-store
subjects:
- kind: ServiceAccount
  name: minio-config
  namespace: system-object-store
roleRef:
  kind: Role
  name: minio-config
  apiGroup: rbac.authorization.k8s.io
