{
 "title": "Quickwit Searchers",
 "tags": [
  "quickwit",
  "searcher"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(quickwit_memory_allocated_bytes,namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(quickwit_search_leaf_searches_splits_total{namespace=\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Split footer cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(quickwit_cache_splitfooter_cache_hits_total{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Total hits"
    },
    {
     "expr": "sum(rate(quickwit_cache_splitfooter_cache_misses_total{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Total miss"
    }
   ]
  },
  {
   "title": "Number of bytes in cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(quickwit_cache_splitfooter_in_cache_num_bytes{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "Split footer"
    },
    {
     "expr": "sum(quickwit_cache_fastfields_in_cache_num_bytes{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "Fast field"
    },
    {
     "expr": "sum(quickwit_cache_partial_request_cache_hits_bytes{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "Partial request"
    },
    {
     "expr": "sum(quickwit_cache_shortlived_in_cache_num_bytes{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "Short lived"
    }
   ]
  },
  {
   "title": "Fast fields cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(quickwit_cache_fastfields_cache_hits_total{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Hit"
    },
    {
     "expr": "sum(rate(quickwit_cache_fastfields_cache_misses_total{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "MIss"
    }
   ]
  },
  {
   "title": "Storage GET requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(quickwit_storage_object_storage_gets_total{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Leaf search splits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "quickwit_search_leaf_searches_splits_total{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Storage GET requests in bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(quickwit_storage_object_storage_download_num_bytes{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "Downloaded bytes"
    }
   ]
  },
  { "title": "Per searcher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }, "repeat": "pod" },
  {
   "title": "Leaf search splits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "quickwit_search_leaf_searches_splits_total{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RSS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Split footer cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(quickwit_cache_splitfooter_cache_hits_total{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "Hit- {{pod}}"
    },
    {
     "expr": "rate(quickwit_cache_splitfooter_cache_misses_total{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "MIss - {{pod}}"
    }
   ]
  },
  {
   "title": "Fast fields cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "rate(quickwit_cache_fastfields_cache_hits_total{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "Hit- {{pod}}"
    },
    {
     "expr": "rate(quickwit_cache_fastfields_cache_misses_total{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "MIss - {{pod}}"
    }
   ]
  }
 ]
}