kind: Feature
apiVersion: blueprints.windsorcli.dev/v1alpha1
metadata:
  name: private-dns
  description: Self-hosted CoreDNS for private DNS zones

when: addons.private_dns.enabled == true

kustomize:
  # CoreDNS server for private DNS zones
  - name: dns
    path: dns
    dependsOn:
      - pki-base
    components:
      - coredns
      - coredns/etcd
      - external-dns
      - external-dns/coredns
      - external-dns/ingress
