kind: Feature
apiVersion: blueprints.windsorcli.dev/v1alpha1
metadata:
  name: talos
  description: "Talos provider basic infrastructure"

when: provider == 'talos'

terraform:
- path: cluster/talos
  parallelism: 1
- path: gitops/flux
  destroy: false

kustomize:

# CSI
- name: csi
  path: csi
  source: core
  dependsOn:
  - policy-resources
  components:
  - openebs
  - openebs/dynamic-localpv
  cleanup:
  - pvcs

# Load Balancer
- name: lb-base
  path: lb/base
  source: core
  dependsOn:
  - policy-resources
  components:
  - metallb
- name: lb-resources
  path: lb/resources
  source: core
  dependsOn:
  - lb-base
  components:
  - metallb/layer2

# Ingress
- name: ingress
  path: ingress
  source: core
  dependsOn:
  - pki-base
  components:
  - nginx
  - nginx/coredns
  - nginx/flux-webhook
  - nginx/web
  cleanup:
  - loadbalancers
  - ingresses
