kind: Feature
apiVersion: blueprints.windsorcli.dev/v1alpha1
metadata:
  name: talos
  description: "Talos provider basic infrastructure"

when: provider == 'generic'

terraform:
- name: cluster
  path: cluster/talos
  parallelism: 1
  inputs:
    cluster_endpoint: ${cluster.endpoint ?? ("https://" + split(values(cluster.controlplanes.nodes)[0].endpoint, ":")[0] + ":6443")}
    cluster_name: talos
    controlplanes: ${values(cluster.controlplanes.nodes)}
    workers: ${values(cluster.workers.nodes)}
    common_config_patches: ${jsonnet("../configs/talos-generic.jsonnet").common_config_patches}
    worker_config_patches: ${jsonnet("../configs/talos-generic.jsonnet").worker_config_patches}
    controlplane_config_patches: ${jsonnet("../configs/talos-generic.jsonnet").controlplane_config_patches}
- name: gitops
  path: gitops/flux
  dependsOn:
    - cluster
  destroy: false

kustomize:

# CSI
- name: csi
  path: csi
  dependsOn:
    - policy-resources
  components:
    - openebs
    - openebs/dynamic-localpv
  substitutions:
    local_volume_path: ${cluster.workers.volumes[0]}
  cleanup:
    - pvcs
  timeout: 20m
  interval: 5m

# Load Balancer
- name: lb-base
  path: lb/base
  when: vm?.driver != 'docker-desktop' && (network.loadbalancer_driver ?? 'kube-vip') == 'metallb'
  dependsOn:
    - policy-resources
  components:
  - metallb
  timeout: 10m
  interval: 5m

- name: lb-resources
  path: lb/resources
  when: vm?.driver != 'docker-desktop'
  dependsOn:
    - ${(network.loadbalancer_driver ?? 'kube-vip') == 'metallb' ? 'lb-base' : 'policy-resources'}
  components:
    - ${network.loadbalancer_driver ?? 'kube-vip'}/${network.loadbalancer_driver == 'kube-vip' ? 'kube-vip' : 'layer2'}
  substitutions:
    loadbalancer_ip_start: ${network.loadbalancer_ips.start}
    loadbalancer_ip_end: ${network.loadbalancer_ips.end}
    loadbalancer_ip_range: ${network.loadbalancer_ips.start + '-' + network.loadbalancer_ips.end}
  timeout: 5m
  interval: 5m

# Ingress
- name: ingress
  path: ingress
  when: vm?.driver != 'docker-desktop'
  dependsOn:
    - pki-base
  components:
    - nginx
    - nginx/web
  timeout: 10m
  interval: 5m
  cleanup:
    - loadbalancers
    - ingresses

# Ingress
- name: ingress
  path: ingress
  when: ingress?.enabled == true && ingress?.driver == 'nginx'
  dependsOn:
    - pki-base
  components:
    - nginx
    - nginx/coredns
    - nginx/web
  cleanup:
    - loadbalancers
    - ingresses
  timeout: 10m
  interval: 5m
