kind: Feature
apiVersion: blueprints.windsorcli.dev/v1alpha1
metadata:
  name: aws
  description: "AWS provider basic infrastructure"

when: provider == 'aws'

terraform:
- name: network
  path: network/aws-vpc
  inputs:
    cidr_block: ${network.cidr_block}
    domain_name: ${dns?.domain ?? ""}
- name: cluster
  path: cluster/aws-eks
  dependsOn:
  - network
- name: cluster-additions
  path: cluster/aws-eks/additions
  dependsOn:
  - cluster
  destroy: false
- name: gitops
  path: gitops/flux
  dependsOn:
  - cluster
  destroy: false

kustomize:

# Ingress
- name: ingress
  path: ingress
  when: ingress.enabled == true && ingress.driver == 'nginx'
  dependsOn:
  - pki-base
  components:
  - nginx
  - nginx/web
  cleanup:
  - loadbalancers
  - ingresses

# CSI
- name: csi
  path: csi
  dependsOn:
  - policy-resources
  components:
  - aws-ebs
  substitutions:
    single_storage_type: ${cluster.storage?.single_storage_type ?? "gp3"}
