kind: Feature
apiVersion: blueprints.windsorcli.dev/v1alpha1
metadata:
  name: platform-incus
  description: Incus compute platform infrastructure

when: vm?.runtime == 'incus' && cluster?.enabled == true

terraform:

- name: compute
  path: compute/incus
  inputs:
    remote: ${providers?.incus?.remote ?? null}
    network_name: "${vm?.driver == 'colima' ? 'incusbr0' : ''}"
    create_network: ${dev != true}
    network_cidr: ${network.cidr_block}
    instances:
      - name: controlplane
        role: controlplane
        count: ${cluster.controlplanes.count ?? 1}
        ipv4: 10.5.0.10/16
        image: windsor:talos/v1.12.0/arm64
        type: virtual-machine
        description: Talos control plane node
        root_disk_size: ${string(cluster.controlplanes.root_disk_size ?? 30) + "GB"}
        limits:
          cpu: ${string(cluster.controlplanes.cpu ?? 2)}
          memory: ${string(cluster.controlplanes.memory ?? 2) + "GB"}
        disks: ${cluster.controlplanes.disks ?? []}
        config:
          user.hostname: ${values(cluster.controlplanes.nodes)[0].hostname ?? "controlplane-1"}
          environment.TALOSSKU: ${string(cluster.controlplanes.cpu ?? 2) + "CPU-" + string(cluster.controlplanes.memory ?? 2) + "GB"}
          raw.qemu: -boot order=c,menu=off
      - name: worker
        role: worker
        count: ${cluster.workers.count ?? 2}
        ipv4: 10.5.0.20/16
        image: windsor:talos/v1.12.0/arm64
        type: virtual-machine
        description: Talos worker node
        root_disk_size: ${string(cluster.workers.root_disk_size ?? 50) + "GB"}
        limits:
          cpu: ${string(cluster.workers.cpu ?? 4)}
          memory: ${string(cluster.workers.memory ?? 4) + "GB"}
        disks: ${cluster.workers.disks ?? []}
        config:
          user.hostname: ${values(cluster.workers.nodes)[0].hostname ?? "worker-1"}
          environment.TALOSSKU: ${string(cluster.workers.cpu ?? 4) + "CPU-" + string(cluster.workers.memory ?? 4) + "GB"}
          raw.qemu: -boot order=c,menu=off

- name: cluster
  path: cluster/talos
  dependsOn:
  - compute
  parallelism: 1
  inputs:
    cluster_endpoint: ${cluster.endpoint ?? ("https://" + terraform_output("compute", "controlplanes")[0].endpoint)}
    cluster_name: talos
    controlplanes: ${terraform_output("compute", "controlplanes") ?? values(cluster.controlplanes.nodes)}
    workers: ${terraform_output("compute", "workers") ?? values(cluster.workers.nodes)}
    common_config_patches: ${jsonnet("../configs/talos-generic.jsonnet").common_config_patches}
    worker_config_patches: ${jsonnet("../configs/talos-generic.jsonnet").worker_config_patches}
    controlplane_config_patches: ${jsonnet("../configs/talos-generic.jsonnet").controlplane_config_patches}
- name: gitops
  path: gitops/flux
  dependsOn:
  - cluster
  destroy: false
