name: Validate terraform docs
on:
  push:

permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Install Task
      uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
      with:
        version: '3.43.3'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate Terraform docs
      run: task docs

    - name: Check for changes
      run: |
        if [[ -n "$(git status --porcelain)" ]]; then
          echo "::error::Terraform documentation is out of date. Please run 'task docs' in the repository."
          git diff
          exit 1
        fi 
