name: WINDSOR UP

on:
  push:
    branches:
      - main
      - windsor-up
  pull_request:
    branches:
      - main
env:
  windsorcli_version: v0.3.2 
  target_repo_owner: windsorcli
  target_repo_name: cli
  public_key_id: 05519B202F65EE4F

jobs:

  windsor-up-test:
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Aqua
        uses: aquaproj/aqua-installer@f13c5d2f0357708d85477aabe50fd3f725528745 # v3.1.0
        with:
          aqua_version: v2.42.2

      - name: Prepare Windsor Project folder
        run: |
          git init
          git config --global init.defaultBranch main
          cat <<EOF > aqua.yaml
          # yaml-language-server: \$schema=https://raw.githubusercontent.com/aquaproj/aqua/main/json-schema/aqua-yaml.json
          # aqua - Declarative CLI Version Manager
          # https://aquaproj.github.io/
          # checksum:
          #   enabled: true
          #   require_checksum: true
          #   supported_envs:
          #   - all
          registries:
            - type: standard
              ref: v4.285.0
          packages:
          - name: hashicorp/terraform@v1.10.3
          - name: siderolabs/talos@v1.9.1
          - name: kubernetes/kubectl@v1.32.0
          - name: docker/cli@v27.4.1
          - name: docker/compose@v2.32.1
          EOF
  
          echo "WINDSOR_PROJECT_ROOT=$(git rev-parse --show-toplevel)" >> $GITHUB_ENV
          
      - name: Install tools
        run: |
          aqua install
      - name: Install Windsor CLI
        run: |
          curl -L -o windsor_${windsorcli_version#v}_linux_amd64.tar.gz https://github.com/windsorcli/cli/releases/download/${windsorcli_version}/windsor_${windsorcli_version#v}_linux_amd64.tar.gz && \
          tar -xzf windsor_${windsorcli_version#v}_linux_amd64.tar.gz -C /usr/local/bin && \
          chmod +x /usr/local/bin/windsor
      - name: Windsor CLI Version Check
        run: |
          which windsor
          windsor version
          expected_version=${windsorcli_version#v}
          actual_version=$(windsor version | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+')
          echo "Expected version: $expected_version"
          echo "Actual version: $actual_version"
          if [ "$actual_version" != "$expected_version" ]; then
            echo "Version mismatch: expected $expected_version but got $actual_version"
            false
          fi

      - name: Windsor Cleanup (REMOVE THIS STEP)
        if: always()
        run: |
          rm -rf contexts
          rm -rf kustomize
          rm -rf terraform 
          rm windsor.yaml
          
      - name: Windsor Init
        run: |
          windsor init local
      - name: Disable DNS
        run: |
          echo "Disabling DNS in windsor.yaml"
          sed -i '/dns:/!b;n;c\      enabled: false' windsor.yaml
          cat windsor.yaml
      - name: Windsor Up
        run: |
          windsor context get
          windsor up --verbose
          
      - name: Verify Kubernetes Nodes
        run: |
          windsor exec -- kubectl get nodes
          windsor exec -- kubectl get pods -A
          windsor exec -- bash -c 'kubectl get pods -A -o json | jq -r ".items[] | select(.status.phase != \"Running\") | .metadata.name" | wc -l' | grep -q '^0$' || (echo "Not all pods are in ready state" && exit 1)
      - name: Windsor Down
        if: always()
        run: |
          windsor down --clean
      - name: Windsor Cleanup
        if: always()
        run: |
          rm -rf /usr/local/bin/windsor
          rm -rf windsor_${windsorcli_version#v}_linux_amd64.tar.gz
          rm -rf *
          sudo rm -rf .windsor
          rm -rf .git
          rm -rf .github
          rm -rf .gitignore
          rm -rf .yamllint
          rm -rf ~/.config/windsor
      - name: Docker Cleanup
        if: always()
        run: |
            docker system prune -a
            docker volume prune
            docker network prune
            docker system prune -a
            rm -rf .volumes
