---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: system-csi
spec:
  values:
    defaultSettings:
      taintToleration: "node-role.kubernetes.io/control-plane:NoSchedule"
